### PR TITLE
fix opentsdb emitter always be running  and fail sending tags whose value contains colon

### LINKED ISSUE #6247: opentsdb emitter occupy 100% core
We use opentsdb emitter to transfer metrics to opentsdb. But we found that the OpentsdbSender occupied 100% of one core. 

image

image
 
image

when the eventQueue is empty, a loop will happen.

### PR DESCRIPTION
**Pull request by QiuMM**
Fix #6247 and #6292 . Opentsdb emitter extension was contributed by me, so I help fix these two issues.

### CODE REVIEW

File: extensions-contrib/opentsdb-emitter/src/main/java/io/druid/emitter/opentsdb/OpentsdbSender.java [hunk 1]
```diff
@@ -40,28 +43,40 @@
    */
   private static final String PATH = "/api/put";
   private static final Logger log = new Logger(OpentsdbSender.class);
+  private static final long FLUSH_TIMEOUT = 60000; // default flush wait 1 min
```
Comment (b-slim) [inline extensions-contrib/opentsdb-emitter/src/main/java/io/druid/emitter/opentsdb/OpentsdbSender.java]: does this means the emitter will block 1 min waiting for the flush to finish?

Comment (QiuMM) [reply extensions-contrib/opentsdb-emitter/src/main/java/io/druid/emitter/opentsdb/OpentsdbSender.java]: Yes it is. This is learned from other emitter extensions, e.g graphite-emitter.

File: extensions-contrib/opentsdb-emitter/src/main/java/io/druid/emitter/opentsdb/OpentsdbSender.java [hunk 2]
```diff
@@ -109,13 +141,11 @@ private void sendEvents()
...
-          OpentsdbEvent event = eventQueue.poll();
-          events.add(event);
-          if (events.size() >= flushThreshold) {
-            sendEvents();
-          }
+      while (!eventQueue.isEmpty() && !scheduler.isShutdown()) {
+        OpentsdbEvent event = eventQueue.poll();
+        events.add(event);
+        if (events.size() >= flushThreshold) {
+          sendEvents();
```
Comment (zhaojiandong) [inline extensions-contrib/opentsdb-emitter/src/main/java/io/druid/emitter/opentsdb/OpentsdbSender.java]: If emitter has large amounts data continuously, eventQueue always has element, this will be multiple EventConsumer tasks at the same time. The object events is a List<OpentsdbEvent>, it's not safe when multiple tasks use it.

Comment (QiuMM) [reply extensions-contrib/opentsdb-emitter/src/main/java/io/druid/emitter/opentsdb/OpentsdbSender.java]: Actually, I used `scheduleWithFixedDelay` not `scheduleAtFixedRate` in my code. There may be two EventConsumer tasks at the same time only in the case of `flush` method being called. And I fixed it.

File: docs/content/development/extensions-contrib/opentsdb-emitter.md [hunk 3]
```diff
@@ -18,10 +18,11 @@ All the configuration parameters for the opentsdb emitter are under `druid.emitt
 |--------|-----------|---------|-------|
 |`druid.emitter.opentsdb.host`|The host of the OpenTSDB server.|yes|none|
 |`druid.emitter.opentsdb.port`|The port of the OpenTSDB server.|yes|none|
-|`druid.emitter.opentsdb.connectionTimeout`|Connection timeout(in milliseconds).|no|2000|
-|`druid.emitter.opentsdb.readTimeout`|Read timeout(in milliseconds).|no|2000|  
+|`druid.emitter.opentsdb.connectionTimeout`|`Jersey client` connection timeout(in milliseconds).|no|2000|
+|`druid.emitter.opentsdb.readTimeout`|`Jersey client` read timeout(in milliseconds).|no|2000|
 |`druid.emitter.opentsdb.flushThreshold`|Queue flushing threshold.(Events will be sent as one batch)|no|100|
 |`druid.emitter.opentsdb.maxQueueSize`|Maximum size of the queue used to buffer events.|no|1000|
+|`druid.emitter.opentsdb.consumeDelay`|Queue consuming delay(in milliseconds).|no|10000|
```
[the remark this answers is not in the document]
Comment (QiuMM) [reply docs/content/development/extensions-contrib/opentsdb-emitter.md]: Done.

**Comment by QiuMM** [comment]
I have tested in my enviroment and worked fine. @b-slim  can you help review this PR again, so we can move on.

**Comment by jon-wei** [comment]
@QiuMM @zhaojiandong I think both #6251 and #6254 would work to fix #6247, but I'm going to go ahead and merge this one since it also has a fix for #6292
