### PR TITLE
Fix hadoop ingestion property handling when using indexers

### LINKED ISSUE #8840: index_hadoop tasks fail on wrong file format when run inside indexer
we have seen this before, it's not replacing `:` and thus HDFS refuses the file as it's illegal.

I guess yet another thing fixed in peon but not in indexer?

```java.lang.IllegalArgumentException: Pathname /druid/indexer/foo/2019-10-29T00:00:00.000Z_2019-10-30T00:00:00.000Z/2019-11-06T19:57:56.216Z/29/index.zip.0 from hdfs://us2/druid/indexer/foo/2019-10-29T00:00:00.000Z_2019-10-30T00:00:00.000Z/2019-11-06T19:57:56.216Z/29/index.zip.0 is not a valid DFS filename.```

### PR DESCRIPTION
**Pull request by jon-wei**
Fixes #8840.

### Description

This PR fixes an issue where the map/reduce jobs created by a HadoopIndexTask running inside an Indexer process didn't pick up configuration properties that were specified in Druid's config files.

Hadoop tasks running in an Indexer process need a reference to the Properties instance created
in PropertiesModule so that the task sees properties that were specified in Druid's config files.

Peon-based tasks didn't have this issue since they have all properties, including config file properties, specified on their command line by ForkingTaskRunner (so they could use System.getProperties() only).

This PR has:
- [x] been self-reviewed.
- [x] added documentation for new or modified features or behaviors.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/incubator-druid/blob/master/licenses.yaml)
- [x] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths.
- [ ] added integration tests.
- [x] been tested in a test Druid cluster.

### CODE REVIEW

File: indexing-hadoop/src/main/java/org/apache/druid/indexer/JobHelper.java [hunk 1]
```diff
@@ -315,11 +315,21 @@ public static void injectDruidProperties(Configuration configuration, List<Strin
     String mapJavaOpts = StringUtils.nullToEmptyNonDruidDataString(configuration.get(MRJobConfig.MAP_JAVA_OPTS));
     String reduceJavaOpts = StringUtils.nullToEmptyNonDruidDataString(configuration.get(MRJobConfig.REDUCE_JAVA_OPTS));
 
-    for (String propName : System.getProperties().stringPropertyNames()) {
```
Comment (suneet-s) [inline indexing-hadoop/src/main/java/org/apache/druid/indexer/JobHelper.java]: nit: Do we want to prevent `System.getProperties()` from being used in this project?

**Comment by jon-wei** [comment]
@jihoonson I had the tutorial hadoop cluster setup with HDFS deep storage, I ran an ingestion task using Indexer and later an ingestion task using MiddleManager, and both tasks succeeded and their segments were published

File: indexing-hadoop/src/main/java/org/apache/druid/indexer/JobHelper.java (hunk 1 above)
Comment (jon-wei) [reply indexing-hadoop/src/main/java/org/apache/druid/indexer/JobHelper.java]: I think it's fine to not have the exclusion for now, the properties handling stuff is pretty localized in `JobHelper` and I'm not 100% sure that there won't be a legitimate need to call `System.getProperties()` ever in the Hadoop module
