### PR TITLE
Fix ITRealtimeIndexTaskTest Flakiness

### LINKED ISSUE #7017: Flaky ITRealtimeIndexTaskTest
```[ERROR] Tests run: 8, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1,419.876 s <<< FAILURE! - in TestSuite
[ERROR] testRealtimeIndexTask(org.apache.druid.tests.indexer.ITRealtimeIndexTaskTest)  Time elapsed: 182.638 s  <<< FAILURE!
java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.jboss.netty.channel.ChannelException: Faulty channel in resource pool
	at org.apache.druid.tests.indexer.ITRealtimeIndexTaskTest.postEvents(ITRealtimeIndexTaskTest.java:119)
	at org.apache.druid.tests.indexer.ITRealtimeIndexTaskTest.testRealtimeIndexTask(ITRealtimeIndexTaskTest.java:57)
Caused by: java.util.concurrent.ExecutionException: org.jboss.netty.channel.ChannelException: Faulty channel in resource pool
	at org.apache.druid.tests.indexer.ITRealtimeIndexTaskTest.postEvents(ITRealtimeIndexTaskTest.java:119)
	at org.apache.druid.tests.indexer.ITRealtimeIndexTaskTest.testRealtimeIndexTask(ITRealtimeIndexTaskTest.java:57)
Caused by: org.jboss.netty.channel.ChannelException: Faulty channel in resource pool
	at org.apache.druid.tests.indexer.ITRealtimeIndexTaskTest.postEvents(ITRealtimeIndexTaskTest.java:119)
	at org.apache.druid.tests.indexer.ITRealtimeIndexTaskTest.testRealtimeIndexTask(ITRealtimeIndexTaskTest.java:57)
Caused by: org.jboss.netty.channel.ChannelException: Failed to handshake with host[https://127.0.0.1:8101]
Caused by: java.nio.channels.ClosedChannelException
```

### LINKED ISSUE #7219: [Flaky Test] ITAppenderatorDriverRealtimeIndexTaskTest testRealtimeIndexTask()
# Affected Version
`master` branch

# Description
Transient failures observed by both me and @jihoonson on Travis.

# Steps to Replicate
Unsure as I don't run ITs on my local machine.  Definitely fails inconsistently on Travis though (e.g. https://travis-ci.org/apache/incubator-druid/jobs/503819087)

# Stack Trace
```
[ERROR] testRealtimeIndexTask(org.apache.druid.tests.indexer.ITAppenderatorDriverRealtimeIndexTaskTest)  Time elapsed: 10.178 s  <<< FAILURE!
java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.jboss.netty.channel.ChannelException: Faulty channel in resource pool
	at org.apache.druid.tests.indexer.ITAppenderatorDriverRealtimeIndexTaskTest.postEvents(ITAppenderatorDriverRealtimeIndexTaskTest.java:108)
	at org.apache.druid.tests.indexer.ITAppenderatorDriverRealtimeIndexTaskTest.testRealtimeIndexTask(ITAppenderatorDriverRealtimeIndexTaskTest.java:57)
Caused by: java.util.concurrent.ExecutionException: org.jboss.netty.channel.ChannelException: Faulty channel in resource pool
	at org.apache.druid.tests.indexer.ITAppenderatorDriverRealtimeIndexTaskTest.postEvents(ITAppenderatorDriverRealtimeIndexTaskTest.java:108)
	at org.apache.druid.tests.indexer.ITAppenderatorDriverRealtimeIndexTaskTest.testRealtimeIndexTask(ITAppenderatorDriverRealtimeIndexTaskTest.java:57)
Caused by: org.jboss.netty.channel.ChannelException: Faulty channel in resource pool
	at org.apache.druid.tests.indexer.ITAppenderatorDriverRealtimeIndexTaskTest.postEvents(ITAppenderatorDriverRealtimeIndexTaskTest.java:108)
	at org.apache.druid.tests.indexer.ITAppenderatorDriverRealtimeIndexTaskTest.testRealtimeIndexTask(ITAppenderatorDriverRealtimeIndexTaskTest.java:57)
Caused by: org.jboss.netty.channel.ChannelException: Failed to handshake with host[https://127.0.0.1:8101]
Caused by: java.nio.channels.ClosedChannelException
```

### PR DESCRIPTION
**Pull request by justinborromeo**
Fixes #7219 and fixes #7017.  ITRealtimeIndexTaskTest has been borking Travis builds.  Adding a 5-second pause before posting events seems to help.  Maybe the test was trying to post events before the peons had fully started?  With this change, the test has passed 5/5 times.

### CODE REVIEW

File: integration-tests/src/test/java/org/apache/druid/tests/indexer/AbstractITRealtimeIndexTaskTest.java [hunk 1]
```diff
@@ -97,6 +97,8 @@ void doTest()
       LOG.info("indexerSpec: [%s]\n", task);
       taskID = indexer.submitTask(task);
 
+      TimeUnit.SECONDS.sleep(5);
```
Comment (gianm) [inline integration-tests/src/test/java/org/apache/druid/tests/indexer/AbstractITRealtimeIndexTaskTest.java]: Could you please include a comment about why this is happening?

Comment (justinborromeo) [reply integration-tests/src/test/java/org/apache/druid/tests/indexer/AbstractITRealtimeIndexTaskTest.java]: Done

Comment (gianm) [reply integration-tests/src/test/java/org/apache/druid/tests/indexer/AbstractITRealtimeIndexTaskTest.java]: This integration test is so gross. No wonder it's flaky. But, okay, sure, fine.

**Comment by leventov** [comment]
I still see flakiness in this test: #8918, should we make the pause longer or rather implement deterministic wait?
