### PR TITLE
Fix equalsAndHashCode in ClientCompactQueryTuningConfig

### LINKED ISSUE #8866: splitHintSpec is not added to ClientCompactQueryTuningConfig's equals(), hashCode(), and toString()
This bug is introduced in #8570, see [diff](https://github.com/apache/incubator-druid/commit/30c15900bec7f4df7a72088ec076223839da258f#diff-d961bf5891534d69c4b45d0c1f69431f).

FYI @jihoonson

### PR DESCRIPTION
**Pull request by suneet-s**
Fixes #8866.

### Description

This change introduces a dependency to EqualsVerifier for the test scope.
The dependency is licensed under Apache 2. The library makes it trivial
to add equals and hashCode checks to prevent bugs like this from happening
in the future

<hr>

This PR has:
- [x] been self-reviewed.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/incubator-druid/blob/master/licenses.yaml)
- [x] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [x] added unit tests or modified existing tests to cover new code paths.

<hr>

### CODE REVIEW

**Comment by suneet-s** [comment]
Licenses not added to the yaml file since the dependency is a test only dependency. It's licensed under apache 2 though - https://github.com/jqno/equalsverifier/blob/master/LICENSE.md

File: server/src/test/java/org/apache/druid/indexing/ClientCompactQueryTuningConfigTest.java [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+package org.apache.druid.indexing;
+
+import nl.jqno.equalsverifier.EqualsVerifier;
+import org.apache.druid.client.indexing.ClientCompactQueryTuningConfig;
+import org.junit.Test;
+
+public class ClientCompactQueryTuningConfigTest
+{
+  @Test
+  public void test_equalsContract()
```
Comment (gianm) [inline server/src/test/java/org/apache/druid/indexing/ClientCompactQueryTuningConfigTest.java]: `testEqualsContract` would be more typical Druid style.
