### PR TITLE
Fix issue that tasks failed because of no sink for identifier

### LINKED ISSUE #6722: tasks failed because of no sink for identifier
Recently, I observed some kafka index tasks failed, below is the log:
```
2018-12-09 20:33:15,603 INFO [task-runner-0-priority-0] io.druid.segment.realtime.appenderator.BaseAppenderatorDriver - Pushing segments in background: [aweme_low_frequency_all_event_2018-12-08T01:00:00.000Z_2018-12-08T02:00:00.000Z_2018-12-09T16:40:28.781Z_58, aweme_low_frequency_all_event_2018-12-09T20:00:00.000Z_2018-12-09T21:00:00.000Z_2018-12-09T20:00:01.734Z_355]
2018-12-09 20:33:15,604 INFO [appenderator_persist_0] io.druid.segment.realtime.appenderator.AppenderatorImpl - Removing sink for segment[aweme_low_frequency_all_event_2018-12-08T01:00:00.000Z_2018-12-08T02:00:00.000Z_2018-12-09T16:40:28.781Z_54].
2018-12-09 20:33:15,620 INFO [appenderator_persist_0] io.druid.segment.realtime.appenderator.AppenderatorImpl - Deleting Index File[var/druid/task/index_kafka_aweme_low_frequency_all_event_da2a8411a415b8b_dfjkpjih/work/persist/aweme_low_frequency_all_event_2018-12-08T01:00:00.000Z_2018-12-08T02:00:00.000Z_2018-12-09T16:40:28.781Z_54]
2018-12-09 20:33:15,604 ERROR [task-runner-0-priority-0] io.druid.indexing.kafka.KafkaIndexTask - Encountered exception in run() before persisting.
io.druid.java.util.common.ISE: No sink for identifier: aweme_low_frequency_all_event_2018-12-08T01:00:00.000Z_2018-12-08T02:00:00.000Z_2018-12-09T16:40:28.781Z_54
	at io.druid.segment.realtime.appenderator.AppenderatorImpl.persistAll(AppenderatorImpl.java:434) ~[druid-server-0.12.2.jar:0.12.2]
	at io.druid.segment.realtime.appenderator.AppenderatorImpl.push(AppenderatorImpl.java:553) ~[druid-server-0.12.2.jar:0.12.2]
	at io.druid.segment.realtime.appenderator.BaseAppenderatorDriver.pushInBackground(BaseAppenderatorDriver.java:470) ~[druid-server-0.12.2.jar:0.12.2]
	at io.druid.segment.realtime.appenderator.StreamAppenderatorDriver.publish(StreamAppenderatorDriver.java:265) ~[druid-server-0.12.2.jar:0.12.2]
	at io.druid.indexing.kafka.KafkaIndexTask.publishAndRegisterHandoff(KafkaIndexTask.java:1243) ~[druid-kafka-indexing-service-0.12.2.jar:0.12.2]
	at io.druid.indexing.kafka.KafkaIndexTask.maybePersistAndPublishSequences(KafkaIndexTask.java:1373) ~[druid-kafka-indexing-service-0.12.2.jar:0.12.2]
	at io.druid.indexing.kafka.KafkaIndexTask.run(KafkaIndexTask.java:544) [druid-kafka-indexing-service-0.12.2.jar:0.12.2]
	at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:444) [druid-indexing-service-0.12.2.jar:0.12.2]
	at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:416) [druid-indexing-service-0.12.2.jar:0.12.2]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
2018-12-09 20:33:15,622 INFO [task-runner-0-priority-0] io.druid.indexing.kafka.KafkaIndexTask - Persisting all pending data
2018-12-09 20:33:15,623 INFO [task-runner-0-priority-0] io.druid.segment.realtime.appenderator.StreamAppenderatorDriver - Persisting data.
2018-12-09 20:33:15,623 INFO [task-runner-0-priority-0] io.druid.segment.realtime.appenderator.AppenderatorImpl - Submitting persist runnable for dataSource[aweme_low_frequency_all_event]
```

According the log and checked the code, I found why this happened.  See below, code 1 is `AppenderatorImpl#persistAll`, code 2 is `AppenderatorImpl#abandonSegment`. Although `sinks` is a ConcurrentHashMap, if `sinks.keySet()` is called at code 1 and after which `sinks.remove(identifier)` is called at code 2, then the for loop go on at code 1, `sinks.get(identifier)` would try to get a object which has been removed. Finally, an exception throwed and task failed.

I think we should add an extra lock to solve this bug.

- code 1
```java
public ListenableFuture<Object> persistAll(@Nullable final Committer committer)
{
    ....
    for (SegmentIdentifier identifier : sinks.keySet()) {
      final Sink sink = sinks.get(identifier);
      if (sink == null) {
        throw new ISE("No sink for identifier: %s", identifier);
      }
      .....
    }
    .....
}
```
- code 2
```java
private ListenableFuture<?> abandonSegment(
      final SegmentIdentifier identifier,
      final Sink sink,
      final boolean removeOnDiskData
  )
{
    .....
    log.info("Removing sink for segment[%s].", identifier);
    sinks.remove(identifier);
    .....
}
```

### PR DESCRIPTION
**Pull request by QiuMM**
Fix #6722.

### CODE REVIEW

**Comment by fjy** [comment]
@QiuMM is it possible to add a test?

**Comment by QiuMM** [comment]
@fjy no, It's hard to simulate since this issue happens infrequently which depends on the execution order of code, i.e affected by thread scheduling.

**Comment by QiuMM** [comment]
FYI, after used this patch, we never see the bug again.

File: server/src/main/java/org/apache/druid/segment/realtime/appenderator/AppenderatorImpl.java [hunk 1]
```diff
@@ -485,8 +486,12 @@ public void clear() throws InterruptedException
     final List<Pair<FireHydrant, SegmentIdentifier>> indexesToPersist = new ArrayList<>();
     int numPersistedRows = 0;
     long bytesPersisted = 0L;
-    for (SegmentIdentifier identifier : sinks.keySet()) {
-      final Sink sink = sinks.get(identifier);
+    Iterator<Map.Entry<SegmentIdentifier, Sink>> iterator = sinks.entrySet().iterator();
+
+    while (iterator.hasNext()) {
```
Comment (jon-wei) [inline server/src/main/java/org/apache/druid/segment/realtime/appenderator/AppenderatorImpl.java]: If I understand correctly, from the code in `abandonSegment`, it looks like the sink removal should not be happening at the same time as a persist (they're both run by the `persistExecutor`).

With this change to using an iterator, I think it would now be possible to persist a Sink that was already abandoned (i.e., `abandonSegment` could remove a Sink after that Sink is returned by iterator.next() in `persistAll`)).

So I'm wondering if it would be more correct to have this "find sinks to persist" code run in one callable together with the actual persist work in the `persistExecutor` as well. 

----

There is also a code block in `push` that has a similar pattern that runs outside of the `pushExecutor` (`abandonSegment` uses `pushBarrier()`), I wonder if there are similar problems there as well:

```
final Map<SegmentIdentifier, Sink> theSinks = new HashMap<>();
    for (final SegmentIdentifier identifier : identifiers) {
      final Sink sink = sinks.get(identifier);
      if (sink == null) {
        throw new ISE("No sink for identifier: %s", identifier);
      }
      theSinks.put(identifier, sink);
      if (sink.finishWriting()) {
        totalRows.addAndGet(-sink.getNumRows());
      }
    }
```

Comment (QiuMM) [reply server/src/main/java/org/apache/druid/segment/realtime/appenderator/AppenderatorImpl.java]: > So I'm wondering if it would be more correct to have this "find sinks to persist" code run in one callable together with the actual persist work in the persistExecutor as well.

you are right, `persistExecutor` using a single thread, I think it will work.

> There is also a code block in push that has a similar pattern that runs outside of the pushExecutor (abandonSegment uses pushBarrier()), I wonder if there are similar problems there as well:

I have never observed any exceptions caused by this. And I think there is no need to worry about it because the program will wait for any outstanding pushes to finish, then abandon the segment inside the persist thread:
```java
.....
// Wait for any outstanding pushes to finish, then abandon the segment inside the persist thread.
    return Futures.transform(
        pushBarrier(),
        new Function<Object, Object>()
        {
          @Nullable
          @Override
        ......
```java

Comment (jon-wei) [reply server/src/main/java/org/apache/druid/segment/realtime/appenderator/AppenderatorImpl.java]: @QiuMM 

> I have never observed any exceptions caused by this. And I think there is no need to worry about it because the program will wait for any outstanding pushes to finish, then abandon the segment inside the persist thread:

I believe you're right that `push` is okay.

In the `persistAll` case I'm guessing what's happening is something like:
1. Task does an incremental publish for some sequence
2. Publish completes, `driver.registerHandoff` adds a callback after handoff finishes that calls `appenderator.drop` -> `abandonSegment`
3. Task does another incremental publish for another sequence
4. Task calls `persistAll` which iterates through sinks, but during this iteration, the handoff callback from the previous incremental publish finishes and removes a sink

For `push`, the input Sinks are read from the Sequence->Segments map instead of looking at the entire set of Sinks, and `StreamAppenderatorDriver.publish` removes the sequence's segments after the publish, so on the next incremental publish, it doesn't have the same problem of accessing Sinks that were handled/dropped as part of the previous incremental publish

Does that sound correct given what you're seeing?

Comment (QiuMM) [reply server/src/main/java/org/apache/druid/segment/realtime/appenderator/AppenderatorImpl.java]: Yes, you are right. I updated this PR to make find sinks to persist run in one callable together with the actual persist work.

File: server/src/main/java/org/apache/druid/segment/realtime/appenderator/AppenderatorImpl.java [hunk 2]
```diff
@@ -521,6 +493,37 @@ public void clear() throws InterruptedException
...
+                }
+              }
+
+              if (sink.swappable()) {
+                indexesToPersist.add(Pair.of(sink.swap(), identifier));
+              }
+            }
+            // NB: The rows are still in memory until they're done persisting, but we only count rows in active indexes.
+            rowsCurrentlyInMemory.addAndGet(-numPersistedRows);
+            bytesCurrentlyInMemory.addAndGet(-bytesPersisted);
```
Comment (QiuMM) [inline server/src/main/java/org/apache/druid/segment/realtime/appenderator/AppenderatorImpl.java]: They need to use `numPersistedRows` and `bytesPersisted`, so I moved them to here. If I define `numPersistedRows` and `bytesPersisted` outside this inner class, they need to be final but they can't be since their value would change.

**Comment by jon-wei** [comment]
@QiuMM there are some real CI failures

**Comment by QiuMM** [comment]
@jon-wei I revert the last commit since it would change the expected behavior and cause the CI failures. 
> Using the iterator would avoid the ISE, but I think it's still possible to persist a Sink that was already abandoned (i.e., abandonSegment could remove a Sink after that Sink is returned by iterator.next() in persistAll)).

I think there is no need to concern this. `abandonSegment` is called in `clear` , `close` and `drop` : 
1. In `clear`, here is the code, it will await the dropping.

```java
        // Drop everything.
        final List<ListenableFuture<?>> futures = Lists.newArrayList();
        for (Map.Entry<SegmentIdentifier, Sink> entry : sinks.entrySet()) {
          futures.add(abandonSegment(entry.getKey(), entry.getValue(), true));
        }

        // Await dropping.
        Futures.allAsList(futures).get();
```
  2. In `close`, it will also await the dropping and shutdown the `persistExecutor`.
  3. In `drop`, it means the handoff operation have been finished, which means the the `hydrant`s 
   have been already swapped and will be ignored to persist.

**Comment by jon-wei** [comment]
@QiuMM Cool, thanks for looking into this
