### PR TITLE
Use current coordinator leader instead of cached one (#6551)

### LINKED ISSUE #6551: Use current leader to query system table instead of the cached value
We found an issue with querying `sys.segments` table on our test cluster when leadership changes for coordinator nodes. The broker keeps querying the incorrect cached coordinator node and the query keeps failing even on shutting down the cached coordinator.
Error from broker.log
```2018-10-29T20:18:23,261 WARN [qtp2097217770-123] org.apache.druid.sql.http.SqlResource - Failed to handle query: SqlQuery{query='select * from (SELECT * FROM sys.segments where datasource='flow0') limit 5000', resultFormat=OBJECT, header=false, context={implyView=sql, implyFeature=query, timeout=300000}}
org.apache.druid.java.util.common.IAE: Next token wasn't a START_ARRAY, was[null] from url [http://ip-172-31-10-101.ec2.internal:8081/druid/coordinator/v1/metadata/segments]
        at org.apache.druid.client.JsonParserIterator.init(JsonParserIterator.java:131) ~[druid-server-0.13.0-incubating.jar:0.13.0-incubating]
        at org.apache.druid.client.JsonParserIterator.hasNext(JsonParserIterator.java:75) ~[druid-server-0.13.0-incubating.jar:0.13.0-incubating]
        at com.google.common.collect.Iterators$7.computeNext(Iterators.java:645) ~[guava-16.0.1.jar:?]
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143) ~[guava-16.0.1.jar:?]
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138) ~[guava-16.0.1.jar:?]
        at org.apache.druid.sql.calcite.schema.SystemSchema$3.hasNext(SystemSchema.java:679) ~[druid-sql-0.13.0-incubating.jar:0.13.0-incubating]
        at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:43) ~[guava-16.0.1.jar:?]
        at com.google.common.collect.Iterators$5.hasNext(Iterators.java:542) ~[guava-16.0.1.jar:?]
        at com.google.common.collect.Iterators$3.hasNext(Iterators.java:159) ~[guava-16.0.1.jar:?]
        at org.apache.calcite.linq4j.Linq4j$IterableEnumerator.moveNext(Linq4j.java:462) ~[calcite-linq4j-1.17.0.jar:1.17.0]
        at org.apache.calcite.linq4j.EnumerableDefaults$24.moveNext(EnumerableDefaults.java:2766) ~[calcite-linq4j-1.17.0.jar:1.17.0]
        at org.apache.calcite.linq4j.EnumerableDefaults$11$1.moveNext(EnumerableDefaults.java:1875) ~[calcite-linq4j-1.17.0.jar:1.17.0]
        at org.apache.calcite.linq4j.EnumerableDefaults$11$1.moveNext(EnumerableDefaults.java:1875) ~[calcite-linq4j-1.17.0.jar:1.17.0]
        at org.apache.calcite.interpreter.Interpreter$EnumeratorSource.receive(Interpreter.java:273) ~[calcite-core-1.17.0.jar:1.17.0]
        at org.apache.calcite.interpreter.FilterNode.run(FilterNode.java:41) ~[calcite-core-1.17.0.jar:1.17.0]
        at org.apache.calcite.interpreter.Interpreter.start(Interpreter.java:130) ~[calcite-core-1.17.0.jar:1.17.0]
        at org.apache.calcite.interpreter.Interpreter.enumerator(Interpreter.java:107) ~[calcite-core-1.17.0.jar:1.17.0]
        at org.apache.druid.sql.calcite.planner.DruidPlanner.lambda$planWithBindableConvention$1(DruidPlanner.java:317) ~[druid-sql-0.13.0-incubating.jar:0.13.0-incubating]
        at org.apache.druid.sql.calcite.planner.PlannerResult.run(PlannerResult.java:46) ~[druid-sql-0.13.0-incubating.jar:0.13.0-incubating]
        at org.apache.druid.sql.http.SqlResource.doPost(SqlResource.java:105) [druid-sql-0.13.0-incubating.jar:0.13.0-incubating]
        at sun.reflect.GeneratedMethodAccessor140.invoke(Unknown Source) ~[?:?]```

### PR DESCRIPTION
**Pull request by surekhasaharan**
Fixes #6551 
Use current coordinator leader instead of cached one when making request
Check the response status and throw exception if not OK before proceeding

### CODE REVIEW

File: server/src/main/java/org/apache/druid/discovery/DruidLeaderClient.java [hunk 1]
```diff
@@ -120,6 +120,17 @@ public void stop()
     log.info("Stopped.");
   }
 
+  /**
+   * Make a Request object aimed at the leader. Throws IOException if the leader cannot be located.
+   *
+   * @param cached Uses cached leader if true, else uses the current leader
+   */
+  public Request makeRequest(HttpMethod httpMethod, String urlPath, boolean cached) throws IOException
```
Comment (jihoonson) [inline server/src/main/java/org/apache/druid/discovery/DruidLeaderClient.java]: Please fix the below `makeRequest` to call this.

Comment (surekhasaharan) [reply server/src/main/java/org/apache/druid/discovery/DruidLeaderClient.java]: ok, done

**Comment by gianm** [comment]
Marking this as 0.13.0 because it seems like a legitimate bug that affects 0.13.0. Please correct me if I am wrong.

**Comment by gianm** [comment]
I mean, it's a bug that affects a new feature (system tables) that we want to be launched as bug-free as possible.

File: server/src/main/java/org/apache/druid/discovery/DruidLeaderClient.java [hunk 2]
```diff
@@ -122,11 +122,21 @@ public void stop()
...
    * Make a Request object aimed at the leader. Throws IOException if the leader cannot be located.
+   *
+   * @param cached Uses cached leader if true, else uses the current leader
    */
-  public Request makeRequest(HttpMethod httpMethod, String urlPath) throws IOException
+  public Request makeRequest(HttpMethod httpMethod, String urlPath, boolean cached) throws IOException
   {
     Preconditions.checkState(lifecycleLock.awaitStarted(1, TimeUnit.MILLISECONDS));
-    return new Request(httpMethod, new URL(StringUtils.format("%s%s", getCurrentKnownLeader(true), urlPath)));
+    return new Request(httpMethod, new URL(StringUtils.format("%s%s", getCurrentKnownLeader(cached), urlPath)));
```
Comment (jon-wei) [inline server/src/main/java/org/apache/druid/discovery/DruidLeaderClient.java]: Mentioning here that the "cache" parameter may not really be necessary, since `pickOneHost` appears to be reading cached state already from `serverDiscoverySelector` or `druidNodeDiscovery`. 

The other callers of makeRequest (with caching true) call DruidLeaderClient.go() which will retry with getCurrentKnownLeader(false) on failures, so they weren't affected by this stale leader issue.

Given that `makeRequest` is used by multiple callers though and we've already cut 0.13.0, I don't think we need to risk changing that behavior (i.e., does getCurrentKnownLeader really needs its own caching) for now though.

**Comment by surekhasaharan** [comment]
I am testing the `BytesAccumulatingResponseHandler` status/description check, will update the PR soon.

File: server/src/main/java/org/apache/druid/discovery/DruidLeaderClient.java (hunk 2 above)
Comment (surekhasaharan) [reply server/src/main/java/org/apache/druid/discovery/DruidLeaderClient.java]: Thanks for checking, agree it may be risky to remove the `cache` from `getCurrentKnownLeader`, can do that post 0.13.0.

File: sql/src/main/java/org/apache/druid/sql/calcite/schema/SystemSchema.java [hunk 3]
```diff
@@ -682,6 +694,49 @@ public void close()
...
+  )
+  {
+    Futures.addCallback(
+        future,
+        new FutureCallback<InputStream>()
+        {
+          @Override
+          public void onSuccess(@Nullable InputStream result)
+          {
+            if (responseHandler.getStatus() == HttpServletResponse.SC_NO_CONTENT) {
```
Comment (jon-wei) [inline sql/src/main/java/org/apache/druid/sql/calcite/schema/SystemSchema.java]: Should `HttpServletResponse.SC_NO_CONTENT` be a failure as well?

Comment (surekhasaharan) [reply sql/src/main/java/org/apache/druid/sql/calcite/schema/SystemSchema.java]: `HttpServletResponse.SC_NO_CONTENT` corresponds to a `204` http status code, and 2xx status codes generally represent success, so I think it should not be a failure. `204` means "The server successfully processed the request and is not returning any content" from [wikipedia](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes)

Comment (jon-wei) [reply sql/src/main/java/org/apache/druid/sql/calcite/schema/SystemSchema.java]: Did you observe that status code being returned on any API calls? It looks like getDatabaseSegments in MetadataResource will always return at least an empty JSON array with status OK, so getting SC_NO_CONTENT seems like an error.

Comment (surekhasaharan) [reply sql/src/main/java/org/apache/druid/sql/calcite/schema/SystemSchema.java]: This part changed with the latest update, I am not checking this status code specifically anymore, so this can be closed i think.

**Comment by dclim** [comment]
@surekhasaharan could you do a backport to 0.13.0 for this?

**Comment by dclim** [comment]
Nevermind, I think Gian might have just done it!
