### PR TITLE
faster flattening for non-existent paths

### LINKED ISSUE #6653: Poor throughput when flattenSpecs refer to missing maps
I observed a cluster earlier today that had poorer than expected throughput for an Avro ingest that had a lot of flattenSpecs. After some profiling I believe it is related to this json-path issue: https://github.com/json-path/JsonPath/issues/396.

This happens when you have a path like `$.x.y.z` but `y` is actually null or missing. So the PropertyPathToken for `z` throws an exception, which is then suppressed (see #5793) and we treat it as a null and move on to the next field. Exceptions, however, are notoriously expensive to construct, so this slows ingestion down. There is a String.format happening as part of the construction, too, which also takes a lot of time (especially relative to the work of evaluating a single path expression).

Maybe we could work around it by claiming (in GenericAvroJsonProvider) that nulls are maps, and then having the mappy methods like getPropertyKeys, getMapValue, etc have do-nothing behavior when passed nulls. If that doesn't work, we might need to land changes in json-path itself, or fork it.

### PR DESCRIPTION
**Pull request by clintropolis**
This adds special json path handling for non-existent paths to circumvent the performance impact caused by json-path/JsonPath#396 by more or less treating `null` as a map and fixes #6653 as much as possible without upstream changes to json-path. This only works for map paths, not arrays as there is some internal code in json-path that catches nulls and throws a `PathNotFoundException` that is unavoidable from our code. Fixed flattening for json, avro, and parquet.

To test performance boost, I modified (but did not commit) the flatten benchmark to test with 5 and 50 non-existent paths.

test of 5 non-existent paths before and after:
```
Benchmark                     Mode  Cnt   Score   Error  Units
FlattenJSONBenchmark.flatten  avgt   25  49.022 ± 0.811  us/op

Benchmark                     Mode  Cnt   Score   Error  Units
FlattenJSONBenchmark.flatten  avgt   25  28.127 ± 4.861  us/op
```
test of 50 non-existent paths before and after:

```
Benchmark                     Mode  Cnt    Score   Error  Units
FlattenJSONBenchmark.flatten  avgt   25  321.887 ± 6.020  us/op

Benchmark                     Mode  Cnt   Score   Error  Units
FlattenJSONBenchmark.flatten  avgt   25  80.608 ± 0.809  us/op
```

### CODE REVIEW

File: extensions-core/avro-extensions/src/main/java/org/apache/druid/data/input/avro/GenericAvroJsonProvider.java [hunk 1]
```diff
@@ -138,7 +141,9 @@ public void setArrayIndex(final Object o, final int i, final Object o1)
   @Override
   public Object getMapValue(final Object o, final String s)
   {
-    if (o instanceof GenericRecord) {
+    if (o == null) {
+      return null;
```
Comment (asdf2014) [inline extensions-core/avro-extensions/src/main/java/org/apache/druid/data/input/avro/GenericAvroJsonProvider.java]: Maybe `UNDEFINED` will be better

File: extensions-core/parquet-extensions/src/main/java/org/apache/druid/data/input/parquet/simple/ParquetGroupJsonProvider.java [hunk 2]
```diff
@@ -105,7 +108,9 @@ public int length(final Object o)
   @Override
   public Object getMapValue(final Object o, final String s)
   {
-    if (o instanceof Map) {
+    if (o == null) {
+      return null;
```
Comment (asdf2014) [inline extensions-core/parquet-extensions/src/main/java/org/apache/druid/data/input/parquet/simple/ParquetGroupJsonProvider.java]: Same.

File: extensions-core/avro-extensions/src/main/java/org/apache/druid/data/input/avro/GenericAvroJsonProvider.java (hunk 1 above)
Comment (clintropolis) [reply extensions-core/avro-extensions/src/main/java/org/apache/druid/data/input/avro/GenericAvroJsonProvider.java]: Actually, using `UNDEFINED` puts it back into the state where it throws `PathNotFoundException` internally, in fixing the tests I lost the performance for json flattening. I've so far returned to using `null` but in a way that doesn't break json path filter expressions, but I'm still exploring to see if there is a more elegant way to handle this, maybe my own `NOT_FOUND` object to handle specially.

Comment (asdf2014) [reply extensions-core/avro-extensions/src/main/java/org/apache/druid/data/input/avro/GenericAvroJsonProvider.java]: > using `UNDEFINED` puts it back into the state where it throws `PathNotFoundException` internally
Okay, I got it. We should avoid creating `PathNotFoundException` instance, because it is expensive operation due to `java.lang.Throwable#fillInStackTrace()`.

> maybe my own `NOT_FOUND` object to handle specially
Sounds good to me. Otherwise, we should add the `@Nullable` annotation.

Comment (asdf2014) [reply extensions-core/avro-extensions/src/main/java/org/apache/druid/data/input/avro/GenericAvroJsonProvider.java]: > using `UNDEFINED` puts it back into the state where it throws `PathNotFoundException` internally

Okay, I understand. We should avoid creating a `PathNotFoundException` instance, because it is an expensive operation because of `java.lang.Throwable#fillInStackTrace()`. What I thought before is that if we return `UNDEFINED` in `getMapValue` method, the program will enter [this](https://github.com/json-path/JsonPath/blob/master/json-path/src/main/java/com/jayway/jsonpath/internal/path/PathToken.java#L45) `if` branch, but since we only  setup `Option.SUPPRESS_EXCEPTIONS` without `Option.REQUIRE_PROPERTIES`, we will still enter enter [this](https://github.com/json-path/JsonPath/blob/master/json-path/src/main/java/com/jayway/jsonpath/internal/path/PathToken.java#L64) branch to avoid creating a `PathNotFoundException`. However, my idea is wrong, it will cause the `EvaluationContextImpl#resultIndex` variable to be equals to zero, and enter [this](https://github.com/json-path/JsonPath/blob/master/json-path/src/main/java/com/jayway/jsonpath/internal/path/EvaluationContextImpl.java#L133) `if` branch, where a `PathNotFoundException` instance will inevitably be created.


> maybe my own `NOT_FOUND` object to handle specially

Sounds good to me. Otherwise, we should add the `@Nullable` annotation.

Comment (clintropolis) [reply extensions-core/avro-extensions/src/main/java/org/apache/druid/data/input/avro/GenericAvroJsonProvider.java]: I tried it out, and using a placeholder object is a bit more tedious than just using `null` but the code is more or less the same, so I think I will leave this PR as is. Do you think `@Nullable` important for methods that we will never likely call directly in the Druid codebase? I don't feel strongly either way and can add it if you or anyone else does, but in this case I don't really think it matters since we are only adjusting these methods to make json-path do the right thing.

Comment (asdf2014) [reply extensions-core/avro-extensions/src/main/java/org/apache/druid/data/input/avro/GenericAvroJsonProvider.java]: Right, I agree with you.

**Comment by gianm** [comment]
Thanks @asdf2014 for reviewing!
