### PR TITLE
Fix double-checked locking in predicate suppliers in BoundDimFilter, InDimFilter

### LINKED ISSUE #8911: Fix double-checked locking in predicate suppliers in BoundDimFilter, InDimFilter, SelectorDimFilter
Similar to #6662. These instances of double-checked locking were not identified in that PR.

For anyone who is willing to do this: please read this thread carefully: https://github.com/apache/incubator-druid/pull/6662#discussion_r236302382

### PR DESCRIPTION
**Pull request by qutang1**
Fixes (partially) #8911.

### Fixed the bug:
Double-checked locking bugs

### CODE REVIEW

File: processing/src/main/java/org/apache/druid/query/filter/BoundDimFilter.java [hunk 1]
```diff
@@ -361,107 +361,107 @@ public String toString()
     class BoundLongPredicateSupplier implements Supplier<DruidLongPredicate>
```
Comment (leventov) [inline processing/src/main/java/org/apache/druid/query/filter/BoundDimFilter.java]: This class is actually a duplicate of `Suppliers.memoize()`. So code can be `return Suppliers.memoize(BoundDimFilter::createLongPredicate)`, assuming `updateSyncedDruidLongPredicate()` is renamed to `createLongPredicate()` and moved one level up.

Same below.

Comment (qutang1) [reply processing/src/main/java/org/apache/druid/query/filter/BoundDimFilter.java]: 1. Modified the code.
2. Have imported eclipse_formatting.xml to the workspace, but  style check still failed.

Comment (qutang1) [reply processing/src/main/java/org/apache/druid/query/filter/BoundDimFilter.java]: Have imported eclipse_formatting.xml to the workspace, but style check still failed.

Comment (leventov) [reply processing/src/main/java/org/apache/druid/query/filter/BoundDimFilter.java]: In this case, it's better to turn off auto-formatting in your IDE and accurately revert unrelated changes.

For a longer-term solution, if you plan to contribution to the project regularly, it's better to consult developers at dev@druid.apache.org

Comment (qutang1) [reply processing/src/main/java/org/apache/druid/query/filter/BoundDimFilter.java]: How about the change of the code logic to u?

Comment (leventov) [reply processing/src/main/java/org/apache/druid/query/filter/BoundDimFilter.java]: LGTM

Comment (qutang1) [reply processing/src/main/java/org/apache/druid/query/filter/BoundDimFilter.java]: > In this case, it's better to turn off auto-formatting in your IDE and accurately revert unrelated changes.
> 
> For a longer-term solution, if you plan to contribution to the project regularly, it's better to consult developers at [dev@druid.apache.org](mailto:dev@druid.apache.org)

In the line 58 of eclipse_formatting.xml, it should be changed to:
<setting id="org.eclipse.jdt.core.formatter.insert_new_line_before_catch_in_try_statement" value="insert"/> instead of "do not insert".  By making this change, "catch" block will be alone on a line to in line with CI standard. Thus eclipse auto-formatting will be correct. I think the xml should be updated although I guess no one else than me is still using eclipse...

Comment (qutang1) [reply processing/src/main/java/org/apache/druid/query/filter/BoundDimFilter.java]: > In this case, it's better to turn off auto-formatting in your IDE and accurately revert unrelated changes.
> 
> For a longer-term solution, if you plan to contribution to the project regularly, it's better to consult developers at [dev@druid.apache.org](mailto:dev@druid.apache.org)

In the line 58 of eclipse_formatting.xml, it should be changed to:
"<setting id="org.eclipse.jdt.core.formatter.insert_new_line_before_catch_in_try_statement" value="insert"/>" instead of "do not insert". By making this change, "catch" block will be alone on a line to in line with CI standard. Thus eclipse auto-formatting will be correct. I think the xml should be updated although I guess no one else than me is still using eclipse...

**Comment by qutang1** [comment]
In the line 58 of eclipse_formatting.xml, it should be changed to:
`<setting id="org.eclipse.jdt.core.formatter.insert_new_line_before_catch_in_try_statement" value="insert"/>` instead of  "do not insert". By making this change, "catch" block will be alone on a line to in line with CI standard. Thus eclipse auto-formatting will be correct. I think the xml should be updated although I guess no one else than me is still using eclipse...

File: processing/src/main/java/org/apache/druid/query/filter/BoundDimFilter.java (hunk 1 above)
Comment (qutang1) [reply processing/src/main/java/org/apache/druid/query/filter/BoundDimFilter.java]: In the line 58 of eclipse_formatting.xml, it should be changed to:
<setting id="org.eclipse.jdt.core.formatter.insert_new_line_before_catch_in_try_statement" value="insert"/> instead of "do not insert". By making this change, "catch" block will be alone on a line to in line with CI standard. Thus eclipse auto-formatting will be correct. I think the xml should be updated although I guess no one else than me is still using eclipse...
