### PR TITLE
Fix avro parser issue while deserializing sketches 

### LINKED ISSUE #6439: Avro parser fails to properly deserialize sketches data
Presently, using the avro parser to index data containing [sketches](http://druid.io/docs/latest/development/extensions-core/datasketches-theta.html) fail with the following error:

```
Caused by: com.yahoo.sketches.SketchesArgumentException: Possible Corruption: Illegal Family ID: 244
	at com.yahoo.sketches.Family.idToFamily(Family.java:195)
	at com.yahoo.sketches.theta.Sketch.wrap(Sketch.java:335)
	at com.yahoo.sketches.theta.Sketch.wrap(Sketch.java:315)
	at com.yahoo.sketches.theta.Sketches.wrapSketch(Sketches.java:86)
	at io.druid.query.aggregation.datasketches.theta.SketchHolder.deserializeFromMemory(SketchHolder.java:237)
	at io.druid.query.aggregation.datasketches.theta.SketchHolder.deserializeFromByteArray(SketchHolder.java:229)
	at io.druid.query.aggregation.datasketches.theta.SketchHolder.deserializeFromBase64EncodedString(SketchHolder.java:224)
	at io.druid.query.aggregation.datasketches.theta.SketchHolder.deserialize(SketchHolder.java:205)
	at io.druid.query.aggregation.datasketches.theta.SketchMergeComplexMetricSerde$1.extractValue(SketchMergeComplexMetricSerde.java:64)
	at io.druid.segment.incremental.IncrementalIndex$1IncrementalIndexInputRowColumnSelectorFactory$1.getObject(IncrementalIndex.java:179)
	at io.druid.query.aggregation.datasketches.theta.SketchAggregator.aggregate(SketchAggregator.java:51)
```

This is caused because the sketches are getting incorrectly deserialized into an arrayish-string like  "[25, 112, 44, 10]" instead of a byte array

### PR DESCRIPTION
**Pull request by a2l007**
Fixes #6439

### CODE REVIEW

**Comment by a2l007** [comment]
Thanks for taking a look @clintropolis 
Yeah I feel this bug wasn't identified earlier probably because nobody else has actually tested this usecase before. I've successfully tested this fix on our internal environment on a couple of avro files with thetasketches.

File: extensions-core/avro-extensions/src/main/java/org/apache/druid/data/input/avro/AvroFlattenerMaker.java [hunk 1]
```diff
@@ -105,7 +104,7 @@ private Object transformValue(final Object field)
       if (binaryAsString) {
         return StringUtils.fromUtf8(((ByteBuffer) field).array());
       } else {
-        return Arrays.toString(((ByteBuffer) field).array());
+        return ((ByteBuffer) field).array();
```
Comment (drcrallen) [inline extensions-core/avro-extensions/src/main/java/org/apache/druid/data/input/avro/AvroFlattenerMaker.java]: a byte buffer is not guaranteed to be array backed, but this is not worse than the prior implementation
