### PR TITLE
fix druid-bloom-filter thread-safety

### LINKED ISSUE #6546: BloomKFilter used by BloomDimFilter not thread-safe leading to unstable results
Experienced unstable results from using `BloomDimFilter` - after investigating it would appear that the [`test` method of the `BloomKFilter` is stateful and not thread-safe](https://github.com/apache/hive/blob/master/storage-api/src/java/org/apache/hive/common/util/BloomKFilter.java#L210) leading to understandably very bizarre behavior when querying a large number of segments.

The hive `BloomFilter` implementation does not seem to have that problem with it's `test` methods, which [only read from the `BitSet`](https://github.com/apache/hive/blob/master/storage-api/src/java/org/apache/hive/common/util/BloomFilter.java#L167), and produces stable results in my testing.

### PR DESCRIPTION
**Pull request by clintropolis**
Alternate approach to what was taken in #6547, instead embedding the `BloomKFilter` implementation in `druid-bloom-filters` extension, and wrapping variables which are re-used instead of re-allocated per function call with `ThreadLocal` to fix the thread safety issues. 

Fixes #6546

The copied `BloomKFilter` is from `hive-storage-api` as of verison 2.7.0 instead of master, since [this commit](https://github.com/apache/hive/commit/87ce36b458350db141c4cb4b6336a9a01796370f#diff-e65fc506757ee058dc951d15a9a526c3L238) seems to have broken backwards compatibility by using 8 bytes instead of 4 to store and test ints/floats. I went with this version specifically to maintain compatibility with the hive version used in the original PR, #6222, despite I think the latest implementation being a bit better since it doesn't use the static variable. The dependency on `hive-storage-api` still exists for use of it's `Murmur3` implementation, though if we embedded that as well we could drop the dependency entirely.

Longer term I think this could prove advantageous having control over the implementation, since it will allow me to implement `ByteBuffer` versions of methods to make #6397 more efficient. 

I collected benchmarks of this implementation of `BloomKFilter` and compared it to `BloomFilter` and they are fairly close, with a slight edge to `BloomKFilter` with larger filters:
```
Benchmark                                     (capacity)   (rows)  Mode  Cnt    Score     Error  Units
BloomKFilterBenchmark.testStringBloomFilter      1000000  3000000  avgt   20  419.952 ±  14.495  ms/op
BloomKFilterBenchmark.testStringBloomFilter     10000000  3000000  avgt   20  632.029 ±  91.746  ms/op
BloomKFilterBenchmark.testStringBloomFilter    100000000  3000000  avgt   20  829.343 ± 214.949  ms/op
BloomKFilterBenchmark.testStringBloomKFilter     1000000  3000000  avgt   20  430.807 ±  17.243  ms/op
BloomKFilterBenchmark.testStringBloomKFilter    10000000  3000000  avgt   20  617.019 ± 171.415  ms/op
BloomKFilterBenchmark.testStringBloomKFilter   100000000  3000000  avgt   20  862.188 ± 270.329  ms/op
```

```
Benchmark                                     (capacity)    (rows)  Mode  Cnt     Score     Error  Units
BloomKFilterBenchmark.testStringBloomFilter      1000000  10000000  avgt   20  1577.867 ±  35.568  ms/op
BloomKFilterBenchmark.testStringBloomFilter     10000000  10000000  avgt   20  2220.278 ±  71.004  ms/op
BloomKFilterBenchmark.testStringBloomFilter    100000000  10000000  avgt   20  2766.451 ± 496.881  ms/op
BloomKFilterBenchmark.testStringBloomKFilter     1000000  10000000  avgt   20  1680.831 ±  39.377  ms/op
BloomKFilterBenchmark.testStringBloomKFilter    10000000  10000000  avgt   20  1983.740 ±  70.657  ms/op
BloomKFilterBenchmark.testStringBloomKFilter   100000000  10000000  avgt   20  2428.820 ± 480.301  ms/op
```

and for reference here is the unmodified `BloomKFilter`, which has similar test speeds as well
```
Benchmark                                     (capacity)    (rows)  Mode  Cnt     Score     Error  Units
BloomKFilterBenchmark.testStringBloomFilter      1000000  10000000  avgt   20  1599.278 ±  70.931  ms/op
BloomKFilterBenchmark.testStringBloomFilter     10000000  10000000  avgt   20  2375.007 ± 149.834  ms/op
BloomKFilterBenchmark.testStringBloomFilter    100000000  10000000  avgt   20  2639.661 ±  84.199  ms/op
BloomKFilterBenchmark.testStringBloomKFilter     1000000  10000000  avgt   20  1673.166 ±  48.810  ms/op
BloomKFilterBenchmark.testStringBloomKFilter    10000000  10000000  avgt   20  2045.913 ±  33.302  ms/op
BloomKFilterBenchmark.testStringBloomKFilter   100000000  10000000  avgt   20  2289.513 ±  44.742  ms/op
```

I am going to test these changes on a test cluster, to ensure they function as expected and correctly resolve #6546, and will add a comment with the results here before we should consider merging.

### CODE REVIEW

**Comment by clintropolis** [comment]
Confirmed working as expected on test cluster

**Comment by b-slim** [comment]
The original intent of PR #6222 , is to build the BloomK sketch in Hive and handed it over to Druid (via the wire as a filter) to filter down the scan, therefore, for this to work we need to make sure that both Hive and Druid are **using the same algorithm for building sketch and probing it**.
This implies that the best way to fix this is to push the fix to Hive Storage API  and drive a storage API release (FYI storage API release is independent from Hive release life cycle hence goes faster). 
In the meantime to not block 0.13  I think we can go with this option where the code is copied over to Druid it self waiting on the release with the bug fix but for the longer term it is better to have it in one place to avoid issues.
@clintropolis if your goal is to build your own bloom filter sketch from scratch for performance reasons or any other goal, then it is better to introduce a new kind of filter.  The other way to do it is to introduce a version blob within the sketch it self to pick the correct serde/probing implementation but this will need way more work...

File: NOTICE [hunk 1]
```diff
@@ -91,4 +91,10 @@ This product contains modified versions of the Dockerfile and related configurat
   * HOMEPAGE:
     * https://github.com/sequenceiq/hadoop-docker/
   * COMMIT TAG:
-    * update this when this patch is committed
\ No newline at end of file
+    * update this when this patch is committed
+
+This product contains code adapted from Apache Hive
```
Comment (b-slim) [inline NOTICE]: there is already one entry for Hive above, to make this more relevant maybe need to add what is copied and commit or release version.

**Comment by clintropolis** [comment]
I don't particularly have a goal at this point other than fixing the thread safety issue that is blocking 0.13. FWIW I did add a [handful of tests](https://github.com/apache/incubator-druid/pull/6584/files#diff-f648c52597a4eada30b95b03337cb918R364) to ensure the copied `BloomKFilter` implementation is compatible with the hive implementation.

The thing that makes it ambiguous of what is the best path forward to me is that I'm not certain the thread safety issues faced here necessarily are concerns with how hive is using this stuff (they may be, but I have no idea and don't want to depend on that). In other words, I'm unsure if the thread safety issue is a hive issue or a druid issue (and also I haven't yet even found how to open an issue on hive yet😛)

Also as I mentioned, the other issue is that the latest version of `BloomKFilter` in hive is incompatible with the current version we are using, which my hive compat test on 'floats' caught because I initially copied `BloomKFilter` from master. I don't know if this is intended or not, the jira associated with the change makes no mention of breaking compatibility so maybe it was accidental.

I agree that if for whatever reason I need to break hive compatibility it will be more appropriate to put in another extension, or yeah, rework this one to support multiple implementations.

File: NOTICE (hunk 1 above)
Comment (clintropolis) [reply NOTICE]: Heh, oops I'm dumb and didn't actually read the `NOTICE` file, just knew i should add something since I copied it from elsewhere, will remove this extra :+1:

File: extensions-core/druid-bloom-filter/src/main/java/org/apache/druid/query/filter/BloomKFilter.java [hunk 2]
```diff
@@ -0,0 +1,530 @@
...
+  }
+
+  public boolean testBytes(byte[] val)
+  {
+    return testBytes(val, 0, val.length);
+  }
+
+  public boolean testBytes(byte[] val, int offset, int length)
+  {
+    long hash64 = val == null ? Murmur3.NULL_HASHCODE :
```
Comment (leventov) [inline extensions-core/druid-bloom-filter/src/main/java/org/apache/druid/query/filter/BloomKFilter.java]: Particular reason why Murmur3 is used? xxHash from https://github.com/OpenHFT/Zero-Allocation-Hashing is much faster and allows to hash for example integers directly garbage-free, without resorting to ThreadLocals such as `BYTE_ARRAY_4`

Comment (clintropolis) [reply extensions-core/druid-bloom-filter/src/main/java/org/apache/druid/query/filter/BloomKFilter.java]: I don't know why specifically this is implemented the way it is here (since this code is copied from hive), but [in the latest version of `BloomKFilter`](https://github.com/apache/hive/blob/master/storage-api/src/java/org/apache/hive/common/util/BloomKFilter.java#L236) `BYTE_ARRAY_4` is no longer used and it uses Murmur3 directly, 

```
public boolean testInt(int val) {
  return testHash(Murmur3.hash64(val));
}
```

However, this seems to be what breaks compatibility with `BloomKFilters` generated with the current version of the hive storage library used by this extension. I suspect this is perhaps an unintended consequence of the modification, as I see [no mention of it in the jira ticket](https://issues.apache.org/jira/browse/HIVE-20101). I haven't looked closely [at the Murmur3 implementation yet](https://github.com/apache/hive/blob/master/storage-api/src/java/org/apache/hive/common/util/Murmur3.java), but it at least looks like it avoids using any patterns like `BYTE_ARRAY_4` in this version of `BloomKFilter`.

Comment (clintropolis) [reply extensions-core/druid-bloom-filter/src/main/java/org/apache/druid/query/filter/BloomKFilter.java]: And to clarify, my modifications to `BloomKFilter` besides formatting changes to make it adhere to style stuff, is limited to using [`ThreadLocal` for the `masks` and `BYTE_ARRAY_4` variables](https://github.com/apache/incubator-druid/pull/6584/files#diff-a7f65879f15d075395ac94c754e1c60cR62).

**Comment by nishantmonu51** [comment]
@clintropolis: Can you also submit a bug and patch against hive for fixing the same in hive-storage-api. I think its ok to have the code copied over here until these changes are merged on hive side and we get a new release. 

Have looked at the code changes, they seem good, will do some more testing internally and update here.

**Comment by clintropolis** [comment]
Sure, I should be able to do that. Is this information at https://cwiki.apache.org/confluence/display/Hive/HowToContribute#HowToContribute still accurate? It looks like I send something to the dev mailing list, then jira, then patch? I can bring up the int/float incompatibility I saw between 2.7.0 and latest as well.

File: extensions-core/druid-bloom-filter/src/main/java/org/apache/druid/query/filter/BloomKFilter.java [hunk 3]
```diff
@@ -0,0 +1,530 @@
...
+import java.io.IOException;
+import java.io.InputStream;
+import java.io.OutputStream;
+import java.util.Arrays;
+
+/**
+ * This is a direct modification of the Apache Hive 'BloomKFilter', found at:
+ * https://github.com/apache/hive/blob/master/storage-api/src/java/org/apache/hive/common/util/BloomKFilter.java
+ * modified to store variables which are re-used instead of re-allocated per call as {@link ThreadLocal} so multiple
+ * threads can share the same filter object. Note that this is snapshot at hive-storag-api version 2.7.0, 3.2.0+ break
```
Comment (b-slim) [inline extensions-core/druid-bloom-filter/src/main/java/org/apache/druid/query/filter/BloomKFilter.java]: am not aware of 3.2.0 release, therefore maybe it is better to reframe this statement or remove 3.2.0.
FYI The incompatibility you are referring too it is not released yet.
Also i recommend adding a TODO, statement to clarify that this is a temporary solution and to remove this class as soon as[ HIVE-20893 ](https://issues.apache.org/jira/browse/HIVE-20893) is fixed and released.

**Comment by clintropolis** [comment]
Thanks @b-slim I will open a PR on github today :+1:

File: extensions-core/druid-bloom-filter/src/main/java/org/apache/druid/query/filter/BloomKFilter.java (hunk 2 above)
Comment (leventov) [reply extensions-core/druid-bloom-filter/src/main/java/org/apache/druid/query/filter/BloomKFilter.java]: @b-slim https://github.com/OpenHFT/Zero-Allocation-Hashing#performance. xxHash is ~2 times faster on long run, with ~2 times shorter bootstrap (6 vs 12 ns) too. Please create issues in Druid or Hive for replacing the algo.

**Comment by clintropolis** [comment]
Updated the PR description to match what was merged

**Comment by dclim** [comment]
@clintropolis could you do a backport to 0.13.0 for this?
