### PR TITLE
Website: stricter replace

### LINKED ISSUE #8592: Docs "edit" link is broken
To reproduce, go to https://druid.apache.org/docs/0.16.0-incubating/design/index.html or https://druid.apache.org/docs/latest/design/index.html and click "edit". The issue is that the extra `/latest/` or `/0.16.0-incubating/` is being passed along to the GitHub URL, leading to broken links like https://github.com/apache/incubator-druid/edit/master/docs/0.16.0-incubating/design/index.md. I think this is related to the `editUrl` in siteConfig.js (currently set to `https://github.com/apache/incubator-druid/edit/master/docs/`).

Btw, a minor related thing: it'd be better to use https://github.com/apache/druid rather than https://github.com/apache/incubator-druid. That way, the links still work when we move to a TLP.

### PR DESCRIPTION
**Pull request by vogievetsky**
Fixes #8592

Restricts URL rewriting to .html files only (avoiding .md links)

### CODE REVIEW

**Comment by vogievetsky** [comment]
@clintropolis ☝️  FYI

File: website/script/fix-path.js [hunk 1]
```diff
@@ -30,8 +30,8 @@ try {
   // Fix doc paths
   replace.sync({
     files: './build/ApacheDruid/docs/**/*.html',
-    from: /\/docs\//g,
-    to: '/docs/' + urlVersion + '/',
+    from: /\/docs\/([^">]+\.html)/g,
```
Comment (gianm) [inline website/script/fix-path.js]: How does this work?

Comment (gianm) [reply website/script/fix-path.js]: (By that I mean, how does this fix the bug #8592?)

Comment (vogievetsky) [reply website/script/fix-path.js]: This script 'fixes' the docs made by the Docusaurus build system to be versioned as part of copying the docs into the website.

it used to look for all instances for the string `/docs/` and turn them into `/docs/0.16.0-incubating/` this is pretty crude.

Now as it happens the git repo has links like this `https://github.com/apache/incubator-druid/edit/master/docs/0.16.0-incubating/design/index.md`

So by coincidence the website and the github both have a `docs` directory.

This script would then rewrite the links generated by the `Edit` button causing the bug.

In this fix I tightened up the matcher regexp to only look for links that end in `.html`. This works because it just so happens that all the docs in GH are `.md` and all the docs that are part of the website are `.html`

Comment (vogievetsky) [reply website/script/fix-path.js]: actually... now that I think about it we could make it even stronger by making sure that we have `"/docs/...` instead of `/docs/...`

Comment (vogievetsky) [reply website/script/fix-path.js]: In fact that is all the is needed... we do not need to constrain only to `.html`!

**Comment by vogievetsky** [comment]
Updated, what a minimal change 💃
