### PR TITLE
segment metadata fallback analysis if no bitmaps

### LINKED ISSUE #7114: Segment metadata queries fail on string columns with disabled bitmaps
# Bug Report

Segment metadata queries return an error on a string column with bitmaps disabled:
`"errorMessage": "error:string_no_bitmap"`

Recent support for disabling bitmaps (https://github.com/apache/incubator-druid/pull/5402) didn't include modification to incubator-druid/processing/src/main/java/org/apache/druid/query/metadata/SegmentAnalyzer.java.

analyzeStringColumn in SegmentAnalyzer.java should be modified to allow disabled bitmaps:

https://github.com/apache/incubator-druid/blob/676f5e6d7f184101b8763e4249b18b237bbe0ec7/processing/src/main/java/org/apache/druid/query/metadata/SegmentAnalyzer.java#L202

### PR DESCRIPTION
**Pull request by clintropolis**
Instead of returning an "error" analysis, instead handle string dimensions without bitmaps by using facilities of `DictionaryEncodedColumn`. Fixes #7114.

### CODE REVIEW

File: processing/src/main/java/org/apache/druid/query/metadata/SegmentAnalyzer.java [hunk 1]
```diff
@@ -198,26 +199,42 @@ private ColumnAnalysis analyzeStringColumn(
...
 
-    if (analyzingMinMax() && cardinality > 0) {
-      min = NullHandling.nullToEmptyIfNeeded(bitmapIndex.getValue(0));
-      max = NullHandling.nullToEmptyIfNeeded(bitmapIndex.getValue(cardinality - 1));
+      if (analyzingMinMax() && cardinality > 0) {
+        min = NullHandling.nullToEmptyIfNeeded(bitmapIndex.getValue(0));
+        max = NullHandling.nullToEmptyIfNeeded(bitmapIndex.getValue(cardinality - 1));
+      }
+    } else if (capabilities.isDictionaryEncoded()) {
+      // fallback if no bitmap index
```
Comment (gianm) [inline processing/src/main/java/org/apache/druid/query/metadata/SegmentAnalyzer.java]: I dunno, maybe we should just remove the `"size"` analysisType. It is nothing but trouble.

File: processing/src/test/java/org/apache/druid/query/metadata/SegmentMetadataQueryTest.java [hunk 2]
```diff
@@ -83,10 +83,15 @@
   public static QueryRunner makeMMappedQueryRunner(
       SegmentId segmentId,
       boolean rollup,
+      boolean bitmaps,
       QueryRunnerFactory factory
   )
   {
-    QueryableIndex index = rollup ? TestIndex.getMMappedTestIndex() : TestIndex.getNoRollupMMappedTestIndex();
+    QueryableIndex index = bitmaps
+                           ? rollup
```
Comment (gianm) [inline processing/src/test/java/org/apache/druid/query/metadata/SegmentMetadataQueryTest.java]: Nested ternaries = 😭. Please consider using normal `if`s.

File: processing/src/main/java/org/apache/druid/query/metadata/SegmentAnalyzer.java (hunk 1 above)
Comment (clintropolis) [reply processing/src/main/java/org/apache/druid/query/metadata/SegmentAnalyzer.java]: Agree. I think it would be interesting to have size be representative of "estimated size in memory" for incremental index, or size in bytes of column in the segment file that is mapped, but what it's computing here seems like basically nonsense for all column types.

File: processing/src/test/java/org/apache/druid/query/metadata/SegmentMetadataQueryTest.java (hunk 2 above)
Comment (clintropolis) [reply processing/src/test/java/org/apache/druid/query/metadata/SegmentMetadataQueryTest.java]: I know, these tests were already painful to slip in a test for this since parameterized, will see if I can clean up. Maybe removing size will help.

File: processing/src/main/java/org/apache/druid/query/metadata/SegmentAnalyzer.java (hunk 1 above)
Comment (egor-ryashin) [reply processing/src/main/java/org/apache/druid/query/metadata/SegmentAnalyzer.java]: > or size in bytes of column in the segment file that is mapped

`dictionary size + bitmap size` I vote for that too.

Comment (clintropolis) [reply processing/src/main/java/org/apache/druid/query/metadata/SegmentAnalyzer.java]: Raised proposal #7124

File: processing/src/test/java/org/apache/druid/segment/TestIndex.java [hunk 3]
```diff
@@ -175,6 +196,17 @@ public static IncrementalIndex getNoRollupIncrementalTestIndex()
     return noRollupRealtimeIndex = makeRealtimeIndex("druid.sample.numeric.tsv", false);
   }
 
+  public static IncrementalIndex getNoBitmapIncrementalTestIndex()
+  {
+    synchronized (log) {
+      if (noBitmapRealtimeIndex != null) {
+        return noBitmapRealtimeIndex;
+      }
+    }
```
Comment (egor-ryashin) [inline processing/src/test/java/org/apache/druid/segment/TestIndex.java]: I know this synchronization pattern was before the change, I'm just confused what it tries to accomplish? ie, if `noBitmapRealtimeIndex` is not created, then all threads can initialize `noBitmapRealtimeIndex` simultaneously, doesn't it look strange?

Comment (clintropolis) [reply processing/src/test/java/org/apache/druid/segment/TestIndex.java]: Good point, I wasn't much attention, will fix.

File: processing/src/main/java/org/apache/druid/query/metadata/SegmentAnalyzer.java [hunk 4]
```diff
@@ -198,26 +199,33 @@ private ColumnAnalysis analyzeStringColumn(
...
-
-    final BitmapIndex bitmapIndex = columnHolder.getBitmapIndex();
-    final int cardinality = bitmapIndex.getCardinality();
-
-    if (analyzingSize()) {
-      for (int i = 0; i < cardinality; ++i) {
-        String value = bitmapIndex.getValue(i);
-        if (value != null) {
-          size += StringUtils.estimatedBinaryLengthAsUTF8(value) * bitmapIndex.getBitmap(bitmapIndex.getIndex(value)).size();
+    int cardinality = 0;
```
Comment (gianm) [inline processing/src/main/java/org/apache/druid/query/metadata/SegmentAnalyzer.java]: My aesthetic sensibility would be to have this be `final` and add a closer `else { }` that sets it to zero, or something. Minor comment though.

File: processing/src/main/java/org/apache/druid/query/metadata/SegmentAnalyzer.java (hunk 1 above)
Comment (gianm) [reply processing/src/main/java/org/apache/druid/query/metadata/SegmentAnalyzer.java]: Until #7124 is sorted, what you're doing here (setting size to 0 when there's no bitmap index) sounds good to me.

File: processing/src/test/java/org/apache/druid/segment/TestIndex.java (hunk 3 above)
Comment (clintropolis) [reply processing/src/test/java/org/apache/druid/segment/TestIndex.java]: Updated to use `Suppliers.memoize` instead. I looked into it, and this code is quite old! It appears to be from the [PR that added timeseries queries to Druid!](https://github.com/apache/incubator-druid/commit/499263386caed48a42fa26c72582fc97f0e64cb9#diff-1bfae2e7948227908d76a8a385844997R199) Thanks for review :+1:

File: processing/src/main/java/org/apache/druid/query/metadata/SegmentAnalyzer.java (hunk 4 above)
Comment (clintropolis) [reply processing/src/main/java/org/apache/druid/query/metadata/SegmentAnalyzer.java]: Changed to do that, thanks for review :metal:
