### PR TITLE
Fix memory problem (OOM/FGC) when expression is used in metricsSpec

### LINKED ISSUE #7715: Memory problem (OOM/FGC) when expression is used in metricsSpec
Affected Version ：0.13.0

The expression field is defined in the metricsSpec of the json.
`
{
        "type": "longSum",
        "name": "sum",
        "discription": "",
        "expression": "..."
`
maxRowsInMemory is set to 300000 and heap size is set to 12g. When  adding 210000 rows to facts calling OnheapIncrementalIndex.add, then JVM is slow down due to frequently FGC（use jstat command）. After replacing the expression with javascript, everything is fine.

`
{
        "type": "javascript",
        "name": "sum",
        "fieldNames": [
            "xxx"
        ],
        "fnAggregate": "...",
        "fnCombine": "...",
        "fnReset": ".."
`

And check the code according to the following stack stace:

```
"task-runner-0-priority-0" #135 daemon prio=5 os_prio=0 tid=0x00007fc49b1f6000 nid=0x43067 runnable [0x00007fc0bfef800
0]
   java.lang.Thread.State: RUNNABLE
        at java.lang.Object.hashCode(Native Method)
        at java.util.HashMap.hash(HashMap.java:338)
        at java.util.HashMap.put(HashMap.java:611)
        at org.apache.druid.math.expr.ExprListenerImpl.exitIdentifierExpr(ExprListenerImpl.java:318)
        at org.apache.druid.math.expr.antlr.ExprParser$IdentifierExprContext.exitRule(ExprParser.java:283)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.exitRule(ParseTreeWalker.java:71)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:54)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
        at org.apache.druid.math.expr.Parser.parse(Parser.java:85)
        at org.apache.druid.math.expr.Parser.parse(Parser.java:72)
        at org.apache.druid.query.aggregation.AggregatorUtil.makeColumnValueSelectorWithDoubleDefault(AggregatorUtil.java:275)
        at org.apache.druid.query.aggregation.SimpleDoubleAggregatorFactory.getDoubleColumnSelector(SimpleDoubleAggregatorFactory.java:68)
        at org.apache.druid.query.aggregation.DoubleSumAggregatorFactory.selector(DoubleSumAggregatorFactory.java:58)
        at org.apache.druid.query.aggregation.DoubleSumAggregatorFactory.selector(DoubleSumAggregatorFactory.java:37)
        at org.apache.druid.query.aggregation.NullableAggregatorFactory.factorize(NullableAggregatorFactory.java:40)
        at org.apache.druid.segment.incremental.OnheapIncrementalIndex.factorizeAggs(OnheapIncrementalIndex.java:234)
        at org.apache.druid.segment.incremental.OnheapIncrementalIndex.addToFacts(OnheapIncrementalIndex.java:166)
        at org.apache.druid.segment.incremental.IncrementalIndex.add(IncrementalIndex.java:610)
        at org.apache.druid.segment.realtime.plumber.Sink.add(Sink.java:181)
        - locked <0x00000004c1c1e1b8> (a java.lang.Object)
        at org.apache.druid.segment.realtime.appenderator.AppenderatorImpl.add(AppenderatorImpl.java:246)
        at org.apache.druid.segment.realtime.appenderator.BaseAppenderatorDriver.append(BaseAppenderatorDriver.java:403)
        at org.apache.druid.segment.realtime.appenderator.StreamAppenderatorDriver.add(StreamAppenderatorDriver.java:180)
        at org.apache.druid.indexing.kafka.IncrementalPublishingKafkaIndexTaskRunner.runInternal(IncrementalPublishingKafkaIndexTaskRunner.java:513)
        at org.apache.druid.indexing.kafka.IncrementalPublishingKafkaIndexTaskRunner.run(IncrementalPublishingKafkaIndexTaskRunner.java:232)
        at org.apache.druid.indexing.kafka.KafkaIndexTask.run(KafkaIndexTask.java:211)
        at org.apache.druid.indexing.overlord.SingleTaskBackgroundRunner$SingleTaskBackgroundRunnerCallable.call(SingleTaskBackgroundRunner.java:421)
        at org.apache.druid.indexing.overlord.SingleTaskBackgroundRunner$SingleTaskBackgroundRunnerCallable.call(SingleTaskBackgroundRunner.java:393)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
```

The cause is AggregatorUtil.makeColumnValueSelectorWithDoubleDefault will parse the same expression every time when a new row is added and the parsed expression is wrapped in the baseSelector actually stored in the array OnheapIncrementalIndex.aggregators.

Druid benchmark is simple tool to reproduce the problem.

1. add the following code in BenchmarkSchemas.java
```
List<AggregatorFactory> basicSchemaIngestAggsExpression = new ArrayList<>();
basicSchemaIngestAggsExpression.add(new CountAggregatorFactory("rows"));
basicSchemaIngestAggsExpression.add(new LongSumAggregatorFactory("sumLongSequential", null, "if(sumLongSequential>0 && dimSequential>100 || dimSequential<10 || metLongSequential>3000,sumLongSequential,0)", ExprMacroTable.nil()));
basicSchemaIngestAggsExpression.add(new LongMaxAggregatorFactory("maxLongUniform", "metLongUniform"));
basicSchemaIngestAggsExpression.add(new DoubleSumAggregatorFactory("sumFloatNormal", null, "if(sumFloatNormal>0 &&  dimSequential>100 || dimSequential<10 || metLongSequential>3000,sumFloatNormal,0)", ExprMacroTable.nil()));
basicSchemaIngestAggsExpression.add(new DoubleMinAggregatorFactory("minFloatZipf", "metFloatZipf"));
basicSchemaIngestAggsExpression.add(new HyperUniquesAggregatorFactory("hyper", "dimHyperUnique"));

BenchmarkSchemaInfo basicSchemaExpression = new BenchmarkSchemaInfo(
    basicSchemaColumns,
    basicSchemaIngestAggsExpression,
    basicSchemaDataInterval,
    true
);

SCHEMA_MAP.put("expression", basicSchemaExpression);
```
2. compile druid project and run benchmark
```shell
mvn clean package -Papache-release,dist,rat -DskipTests
cd benchmarks
java -jar target/benchmarks.jar -jvmArgs "-Xms2G -Xmx2G" -f 2 -w 1 -r 1 -p rowsPerSegment=400000 -p schema=expression -p rollup=true IndexIngestionBenchmark 
```
3. using jstat command to monitor 
```shell
jstat -gcutil <pid> 1000
```

### PR DESCRIPTION
**Pull request by viongpanzi**
Fix #7715 

In this pull request:
1. Memorize the computing of Parser.parse
2. Add some test cases
3. Add expression schema in BenchmarkSchemas 

With newest code, steps in #7715 used to reproduce the issue are all successful and complete fast.

The benchmark result (As the complexity of the expression to be processed increases, the processing time also increases proportionately using old codes):

before
```
Benchmark                        (rollup)  (rowsPerSegment)    (schema)  Mode  Cnt        Score        Error  Units
IndexIngestionBenchmark.addRows      true             75000  expression  avgt   25  3346195.975 ±  39913.271  us/op
IndexIngestionBenchmark.addRows     false             75000  expression  avgt   25  3668692.912 ± 320426.049  us/op
```

patch
```
Benchmark                        (rollup)  (rowsPerSegment)    (schema)  Mode  Cnt       Score       Error  Units
IndexIngestionBenchmark.addRows      true             75000  expression  avgt   25  701224.282 ± 35916.176  us/op
IndexIngestionBenchmark.addRows     false             75000  expression  avgt   25  680209.466 ± 25039.032  us/op
```

### CODE REVIEW

File: core/src/main/java/org/apache/druid/math/expr/Parser.java [hunk 1]
```diff
@@ -75,6 +75,9 @@ public static Expr parse(String in, ExprMacroTable macroTable)
   @VisibleForTesting
   static Expr parse(String in, ExprMacroTable macroTable, boolean withFlatten)
   {
+    if (log.isDebugEnabled()) {
```
Comment (himanshug) [inline core/src/main/java/org/apache/druid/math/expr/Parser.java]: log.debug(..) has this check inside it , you can use string format instead of string concatenation and remove this check.

File: processing/src/main/java/org/apache/druid/query/aggregation/AggregatorUtil.java [hunk 2]
```diff
@@ -196,7 +246,7 @@ static BaseFloatColumnValueSelector makeColumnValueSelectorWithFloatDefault(
     if (fieldName != null) {
       return metricFactory.makeColumnValueSelector(fieldName);
     } else {
-      final Expr expr = Parser.parse(fieldExpression, macroTable);
+      final Expr expr = parseIfAbsent(fieldExpression, macroTable);
```
Comment (himanshug) [inline processing/src/main/java/org/apache/druid/query/aggregation/AggregatorUtil.java]: would be better to not have explicit cache added in this class. Instead, if you change arguments of this(and other similar methods) to...

```
  static BaseFloatColumnValueSelector makeColumnValueSelectorWithFloatDefault(
      final ColumnSelectorFactory metricFactory,
      @Nullable final String fieldName,
      @Nullable final Expr fieldExpression,
      final float nullValue
  )
```

and let caching happen in `SimpleXXAggregatorFactory` classes . Don't parse in the constructor of those classes because those objects could be created in many places where they wouldn't need parsed expression, so do the parsing lazily.

File: core/src/main/java/org/apache/druid/math/expr/Parser.java (hunk 1 above)
Comment (himanshug) [reply core/src/main/java/org/apache/druid/math/expr/Parser.java]: also, not sure if you really need this log at all.

Comment (viongpanzi) [reply core/src/main/java/org/apache/druid/math/expr/Parser.java]: @himanshug Thanks for your advice. I'll remove this check in the next commit. This is just for debug purpose.

File: processing/src/main/java/org/apache/druid/query/aggregation/AggregatorUtil.java (hunk 2 above)
Comment (viongpanzi) [reply processing/src/main/java/org/apache/druid/query/aggregation/AggregatorUtil.java]: @himanshug Good advice! I'll push a new commit when I resolve it.

Comment (viongpanzi) [reply processing/src/main/java/org/apache/druid/query/aggregation/AggregatorUtil.java]: @himanshug Would it be better if we move the cache to the Parser class and add a new method like parseIfAbsent? Otherwise, we need to add cache in  SimpleXXAggregatorFactory, respectively.

```
public abstract class SimpleFloatAggregatorFactory extends NullableAggregatorFactory<BaseFloatColumnValueSelector>
{
  protected final String name;
  @Nullable
  protected final String fieldName;
  @Nullable
  protected final String expression;
  protected final ExprMacroTable macroTable;
  protected final Supplier<Expr> fieldExpression;

  public SimpleFloatAggregatorFactory(
      ExprMacroTable macroTable,
      String name,
      @Nullable final String fieldName,
      @Nullable String expression
  )
  {
    this.macroTable = macroTable;
    this.name = name;
    this.fieldName = fieldName;
    this.expression = expression;
    this.fieldExpression = () -> expression == null ? null : Parser.parseIfAbsent(expression, macroTable);
```

Comment (himanshug) [reply processing/src/main/java/org/apache/druid/query/aggregation/AggregatorUtil.java]: sent a PR to your branch, pls merge that. I meant to remove cache altogether and tie lifetime of parsed expression to the object holding it.

Comment (viongpanzi) [reply processing/src/main/java/org/apache/druid/query/aggregation/AggregatorUtil.java]: New commit is pushed. 
Remove the loading cache.

**Comment by viongpanzi** [comment]
Update the description of this pr according to the newest code.

**Comment by viongpanzi** [comment]
@gianm would you like to look at this patch?

File: processing/src/main/java/org/apache/druid/query/aggregation/AggregatorUtil.java (hunk 2 above)
Comment (viongpanzi) [reply processing/src/main/java/org/apache/druid/query/aggregation/AggregatorUtil.java]: @himanshug sorry for the delayed update! Can you review this patch again?

Comment (himanshug) [reply processing/src/main/java/org/apache/druid/query/aggregation/AggregatorUtil.java]: @viongpanzi  changes look good, thanks.

also, not sure if you know/understood but when I raised https://github.com/viongpanzi/incubator-druid/pull/1 , I would expect you to merge the PR instead of copying the changes so that original commit stays alongside your commits . something for next time :)

Comment (viongpanzi) [reply processing/src/main/java/org/apache/druid/query/aggregation/AggregatorUtil.java]: @himanshug Thanks for your review. Sorry for the misunderstood! I need to learn more about github and I'll pay attention next time.
