### PR TITLE
SQL: Finalize aggregations for inner queries when necessary.

### LINKED ISSUE #5779: HLL in inner group by does not get finalized
I try running this query to compute average daily active users on the wikipedia dataset:

```sql
SELECT AVG("t_unique") AS "AvgDAU"
FROM (SELECT
      TIME_FLOOR("__time", 'P1D'),
      APPROX_COUNT_DISTINCT("user_unique") AS "t_unique"  
    FROM "wikipedia"
    GROUP BY 1
)
```

I get the error: `Unknown type[class io.druid.hll.HLLCV1] for field` probably because not finalizer is added.

Same result if you substitute "user_unique" (an HLL column) with "user" (a string column)

This is the explain plan:

```
DruidOuterQueryRel(query=[{"queryType":"timeseries","dataSource":{"type":"table","name":"__subquery__"},"intervals":{"type":"intervals","intervals":["-146136543-09-08T08:23:32.096Z/146140482-04-24T15:36:27.903Z"]},"descending":false,"virtualColumns":[],"filter":null,"granularity":{"type":"all"},"aggregations":[{"type":"longSum","name":"a0:sum","fieldName":"t_unique","expression":null},{"type":"count","name":"a0:count"}],"postAggregations":[{"type":"arithmetic","name":"a0","fn":"quotient","fields":[{"type":"fieldAccess","name":null,"fieldName":"a0:sum"},{"type":"fieldAccess","name":null,"fieldName":"a0:count"}],"ordering":null}],"context":{"skipEmptyBuckets":true,"timeout":300000}}], signature=[{a0:LONG}])
     DruidQueryRel(query=[{"queryType":"timeseries","dataSource":{"type":"table","name":"wikipedia"},"intervals":{"type":"intervals","intervals":["-146136543-09-08T08:23:32.096Z/146140482-04-24T15:36:27.903Z"]},"descending":false,"virtualColumns":[],"filter":null,"granularity":"DAY","aggregations":[{"type":"hyperUnique","name":"a0","fieldName":"user_unique","isInputHyperUnique":false,"round":true}],"postAggregations":[],"context":{"skipEmptyBuckets":true,"timeout":300000}}], signature=[{d0:LONG, a0:LONG}])
```

Please finalize

### PR DESCRIPTION
**Pull request by gianm**
Fixes #5779.

### CODE REVIEW

File: sql/src/test/java/io/druid/sql/calcite/planner/CalcitesTest.java [hunk 1]
```diff
@@ -42,14 +42,14 @@ public void testEscapeStringLiteral()
   @Test
   public void testFindOutputNamePrefix()
```
Comment (nishantmonu51) [inline sql/src/test/java/io/druid/sql/calcite/planner/CalcitesTest.java]: nit rename test method name to testFindUnusedPrefix.

Comment (gianm) [reply sql/src/test/java/io/druid/sql/calcite/planner/CalcitesTest.java]: Fixed that and re-pushed.

Comment (nishantmonu51) [reply sql/src/test/java/io/druid/sql/calcite/planner/CalcitesTest.java]: Thanks @gianm
