### PR TITLE
overhaul 'druid-parquet-extensions' module, promoting from 'contrib' to 'core'

### LINKED ISSUE #5150: Druid-parquet-extensions fails on timestamps (stored as INT96) in parquet files
I am trying to use the druid-parquet-extensions to ingest parquet data in druid. As per my understanding parquet uses INT96 as the datatype for timestamps:

optional int96 logged_at

Trying to read this parquet files in hadoop index job throws an error that INT96 not supported. It looks like INT96 field may need to be read as an byte array, has anyone seen similar error, suggestion?

I am using druid 0.11.0, here is the detailed stack trace:

```
Caused by: java.lang.IllegalArgumentException: INT96 not yet implemented.
    at org.apache.parquet.avro.AvroSchemaConverter$1.convertINT96(AvroSchemaConverter.java:279) ~[parquet-avro-1.8.2.jar:0.11.0.1]
    at org.apache.parquet.avro.AvroSchemaConverter$1.convertINT96(AvroSchemaConverter.java:264) ~[parquet-avro-1.8.2.jar:0.11.0.1]
    at org.apache.parquet.schema.PrimitiveType$PrimitiveTypeName$7.convert(PrimitiveType.java:223) ~[parquet-column-1.8.2.jar:1.8.2]
    at org.apache.parquet.avro.AvroSchemaConverter.convertField(AvroSchemaConverter.java:263) ~[parquet-avro-1.8.2.jar:0.11.0.1]
    at org.apache.parquet.avro.AvroSchemaConverter.convertFields(AvroSchemaConverter.java:241) ~[parquet-avro-1.8.2.jar:0.11.0.1]
    at org.apache.parquet.avro.AvroSchemaConverter.convert(AvroSchemaConverter.java:231) ~[parquet-avro-1.8.2.jar:0.11.0.1]
    at org.apache.parquet.avro.DruidParquetReadSupport.prepareForRead(DruidParquetReadSupport.java:98) ~[druid-parquet-extensions-0.11.0.1.jar:0.11.0.1]
    at org.apache.parquet.hadoop.InternalParquetRecordReader.initialize(InternalParquetRecordReader.java:175) ~[parquet-hadoop-1.8.2.jar:1.8.2]
    at org.apache.parquet.hadoop.ParquetRecordReader.initializeInternalReader(ParquetRecordReader.java:190) ~[parquet-hadoop-1.8.2.jar:1.8.2]
    at org.apache.parquet.hadoop.ParquetRecordReader.initialize(ParquetRecordReader.java:147) ~[parquet-hadoop-1.8.2.jar:1.8.2]
    at org.apache.hadoop.mapreduce.lib.input.DelegatingRecordReader.initialize(DelegatingRecordReader.java:84) ~[hadoop-mapreduce-client-core-2.7.3.2.5.3.0-37.jar:?]
    at org.apache.hadoop.mapred.MapTask$NewTrackingRecordReader.initialize(MapTask.java:548) ~[hadoop-mapreduce-client-core-2.7.3.2.5.3.0-37.jar:?]
    at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:786) ~[hadoop-mapreduce-client-core-2.7.3.2.5.3.0-37.jar:?]
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341) ~[hadoop-mapreduce-client-core-2.7.3.2.5.3.0-37.jar:?]
    at org.apache.hadoop.mapred.LocalJobRunner$Job$MapTaskRunnable.run(LocalJobRunner.java:243) ~[hadoop-mapreduce-client-common-2.7.3.2.5.3.0-37.jar:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_141]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_141]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_141]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_141]
    at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_141] 
```

### LINKED ISSUE #5433: Data changes during ingestion of Array<String> using druid-parquet-extensions
I am using **druid-0.11.0**, with **druid-avro-extension:0.11.0** and **druid-parquet-extension:0.10.0** and **druid-hdfs-storage:0.11.0**.

My data contained a column which was of type `Array<String>`. If data for this column contained value `["str1", "str2", "str3"]` then after ingestion the same becomes` ["{\"element\": \"str1\"}", "{\"element\": \"str2\"}", "{\"element\": \"str3\"}"]`.

The actual data for the same is stored in hdfs in parquet with snappy compression, and the parser for the same is used during ingestion. This issue persisted even after I changed the compression to gzip.

When the compression was removed in hdfs the data for the column post ingestion became ` ["{\"array_element\": \"str1\"}", "{\"array_element\": \"str2\"}", "{\"array_element\": \"str3\"}"]`.

The same data was earlier being properly ingested into druid when the data was in avro format with gzip compression with druid's avro parser.

I am attaching the ingestionSpec alongside.
[druid_ingestion_schema.txt](https://github.com/druid-io/druid/files/1763022/druid_ingestion_schema.txt)

### PR DESCRIPTION
**Pull request by clintropolis**
This PR promotes the `druid-parquet-extensions` module from 'contrib' to 'core' and introduces a new hadoop parser that is not based on converting to avro first, instead using the `SimpleGroup` based reference implementation of the `parquet-column` package of `parquet-mr`. This is likely not be the best or most efficient way to parse and convert parquet files... but its raw structure suited my needs of supporting converting `int96` timestamp columns into longs (for #5150) and additionally provide the ability to support a `flattenSpec`.

changes:
* `druid-parquet-extensions` now provides 2 types of hadoop parsers, `parquet` and `parquet-avro`, which use `org.apache.druid.data.input.parquet.simple.DruidParquetInputFormat` and `org.apache.druid.data.input.parquet.avro.DruidParquetAvroInputFormat` hadoop input formats respectively. 
* `parquet` and `parquet-avro` parsers now both support `flattenSpec` by specifying `parquet` and `avro` in the `parseSpec` respectively. `parquet-avro` re-uses the `druid-avro-extensions` spec and flattener. There may be minor behavior differences in how parquet logical types are handled.
* extracted abstract type `NestedDataParseSpec<TFlattenSpec>` for ParseSpecs which support a `flattenSpec` property, used by `JSONParseSpec`, `AvroParseSpec`, and `ParquetParseSpec` (also introduced in this PR)
* lightly modified behavior of `avro` flattener auto field discovery to be more discerning about arrays (only primitive arrays are now considered) and to allow nullable primitive fields to be picked up. The array thing might need to be called out, since previously it would have the `toString` array contents of complex types, which I don't think is correct behavior, but could trip up anyone relying on that to happen.
* adds many tests and parquet test files ("donated" from [spark-sql tests here](https://github.com/apache/spark/tree/master/sql/core/src/test/resources/test-data)) to ensure conversion correctness (though probably still not enough)

On top of all of the added tests, I've lightly tested both parsers on a local druid/hadoop cluster on my laptop. 

Fixes #5150 with `parquet` parser (`parquet-avro` still does not support INT96)
Fixes #5433 by defaulting `"parquet.avro.add-list-element-records":"false"` for `parquet-avro`

### CODE REVIEW

**Comment by amalakar** [comment]
The `INT96` bug has been one of the annoying issues we have had. It had caused us to convert to csv first before loading into druid. Looking forward to this fix.

**Comment by clintropolis** [comment]
FYI I'm working on refactoring/parameterizing tests to cut down on the amount of dupe and json, but haven't had the chance to finish yet.

File: extensions-core/parquet-extensions/src/main/java/org/apache/druid/data/input/parquet/simple/ParquetGroupFlattenerMaker.java [hunk 1]
```diff
@@ -0,0 +1,126 @@
...
+import javax.annotation.Nullable;
+import java.util.EnumSet;
+import java.util.List;
+import java.util.Set;
+import java.util.function.Function;
+import java.util.stream.Collectors;
+
+public class ParquetGroupFlattenerMaker implements ObjectFlatteners.FlattenerMaker<Group>
+{
+  private static final MappingProvider DEFAULT_MAPPING_PROVIDER = new MappingProvider()
```
Comment (jon-wei) [inline extensions-core/parquet-extensions/src/main/java/org/apache/druid/data/input/parquet/simple/ParquetGroupFlattenerMaker.java]: This looks the same as `GenericAvroMappingProvider`, can these be merged?

File: extensions-core/parquet-extensions/src/main/java/org/apache/druid/data/input/parquet/simple/ParquetGroupFlattenerMaker.java [hunk 2]
```diff
@@ -0,0 +1,126 @@
...
+      Object val = jsonPath.read(record, jsonPathConfiguration);
+      return finalizeConversion(val);
+    };
+  }
+
+  @Nullable
+  @Override
+  public Function<Group, Object> makeJsonQueryExtractor(String expr)
+  {
+    return null;
```
Comment (jon-wei) [inline extensions-core/parquet-extensions/src/main/java/org/apache/druid/data/input/parquet/simple/ParquetGroupFlattenerMaker.java]: I think it'd be better to throw an exception here

File: extensions-core/avro-extensions/src/main/java/org/apache/druid/data/input/avro/AvroFlattenerMaker.java [hunk 3]
```diff
@@ -50,13 +50,37 @@
...
+  private static boolean isPrimitiveArray(Schema schema)
+  {
+    return schema.getType().equals(Schema.Type.ARRAY) && isPrimitive(schema.getElementType());
+  }
+
+  private static boolean isOptionalPrimitive(Schema schema)
+  {
+    return schema.getType().equals(Schema.Type.UNION) &&
+           schema.getTypes().size() == 2 &&
+           schema.getTypes().get(0).getType().equals(Schema.Type.NULL) &&
```
Comment (jon-wei) [inline extensions-core/avro-extensions/src/main/java/org/apache/druid/data/input/avro/AvroFlattenerMaker.java]: in the union types, is the NULL type guaranteed to appear before the actual type?

File: extensions-core/parquet-extensions/src/main/java/org/apache/druid/data/input/parquet/simple/DruidParquetReadSupport.java [hunk 4]
```diff
@@ -0,0 +1,95 @@
...
+  private MessageType getPartialReadSchema(InitContext context)
+  {
+    MessageType fullSchema = context.getFileSchema();
+
+    String name = fullSchema.getName();
+
+    HadoopDruidIndexerConfig config = HadoopDruidIndexerConfig.fromConfiguration(context.getConfiguration());
+    ParseSpec parseSpec = config.getParser().getParseSpec();
+
+    // todo: this is kind of lame, maybe we can still trim what we read if we
```
Comment (jon-wei) [inline extensions-core/parquet-extensions/src/main/java/org/apache/druid/data/input/parquet/simple/DruidParquetReadSupport.java]: hm, rather than parsing the flattenspec, maybe this could be supported with a "requiredFields" method on flatten specs, but I would remove the "todo" part for now

File: extensions-core/avro-extensions/src/main/java/org/apache/druid/data/input/avro/AvroFlattenerMaker.java (hunk 3 above)
Comment (clintropolis) [reply extensions-core/avro-extensions/src/main/java/org/apache/druid/data/input/avro/AvroFlattenerMaker.java]: Hmm, i'm actually not certain it's guaranteed, from spec

>Unions
Unions, as mentioned above, are represented using JSON arrays. For example, ["null", "string"] declares a schema which may be either a null or string.

>(Note that when a default value is specified for a record field whose type is a union, the type of the default value must match the first element of the union. Thus, for unions containing "null", the "null" is usually listed first, since the default value of such unions is typically null.)

>Unions may not contain more than one schema with the same type, except for the named types record, fixed and enum. For example, unions containing two array types or two map types are not permitted, but two types with different names are permitted. (Names permit efficient resolution when reading and writing unions.)

>Unions may not immediately contain other unions.

I'm actually not certain what would be best to do in this case, but since we didn't support nullable fields at all previously afaict maybe it's ok.

Comment (jon-wei) [reply extensions-core/avro-extensions/src/main/java/org/apache/druid/data/input/avro/AvroFlattenerMaker.java]: hm, from that it sounds like [primitive, null] is valid if the default is non-null then, can you make this check non-order dependent?

File: extensions-core/parquet-extensions/src/main/java/org/apache/druid/data/input/parquet/simple/ParquetGroupFlattenerMaker.java (hunk 1 above)
Comment (clintropolis) [reply extensions-core/parquet-extensions/src/main/java/org/apache/druid/data/input/parquet/simple/ParquetGroupFlattenerMaker.java]: Oops, forgot about this. I was planning to make a default do nothing implementation since that is what these are both doing :+1:

File: extensions-core/parquet-extensions/src/main/java/org/apache/druid/data/input/parquet/simple/ParquetGroupFlattenerMaker.java [hunk 5]
```diff
@@ -0,0 +1,126 @@
...
+   * @return
+   */
+  private Object finalizeConversion(Object o)
+  {
+    // conversion can leave 'wrapped' list primitives
+    if (ParquetGroupConverter.isWrappedListPrimitive(o)) {
+      return converter.unwrapListPrimitive(o);
+    } else if (o instanceof List) {
+      List<Object> asList = (List<Object>) o;
+      if (asList.stream().allMatch(ParquetGroupConverter::isWrappedListPrimitive)) {
```
Comment (jon-wei) [inline extensions-core/parquet-extensions/src/main/java/org/apache/druid/data/input/parquet/simple/ParquetGroupFlattenerMaker.java]: Are there cases where such lists have some items "wrapped" but some items "unwrapped"? 

I'm wondering if the allMatch isWrappedListPrimitive check is necessary, is it possible and correct to remove that pass and just unwrap anything that's wrapped in the list?

Comment (clintropolis) [reply extensions-core/parquet-extensions/src/main/java/org/apache/druid/data/input/parquet/simple/ParquetGroupFlattenerMaker.java]: I don't know what is allowed to happen, but I think if the list is not homogeneous it is safer to not do this conversion rather than do a partial conversion. Leaving this as is for now

**Comment by amalakar** [comment]
Is this PR going to be merged soon? Would love to try it out.

**Comment by dclim** [comment]
Change to index spec inputFormat (org.apache.druid.data.input.parquet.simple.DruidParquetInputFormat) should be called out in release notes
