### PR TITLE
Broker backpressure.

### LINKED ISSUE #4933: Backpressure for broker-to-historical communication
If the result set size is very large and the client making the query is not pulling the results out fast enough, brokers can go OOM. This is because the broker lacks backpressure for large result sets, and they can "pile up" in memory. I believe that the specific part lacking backpressure is the collection and merging of results from individual historical (and realtime) nodes.

This is mostly an issue with scan queries and groupBy queries, which can generate large result sets.

When implementing backpressure it would be important to consider the effect this may have on the historical nodes. Backpressure would presumably extend all the way down to them, and in that case, would block threads their http server pools.

Related: #4229, which introduced `maxScatterGatherBytes` as a kind of workaround to prevent broker crashes (although it will fail queries).

Also related: #4865, a symptom.

### PR DESCRIPTION
**Pull request by gianm**
Adds a new property "druid.broker.http.maxQueuedBytes" and a new context
parameter "maxQueuedBytes". Both represent a maximum number of bytes queued
per query before exerting backpressure on the channel to the data server.

I tested this by running on a modest cluster (6 historicals) and doing an unlimited,
unfiltered Scan query via SQL (`select * from tbl`). The query ran for about half an
hour and managed to fetch almost 20GB of results without OOMing the broker.
Without this patch, the same query quickly OOMed the broker.

See HttpResponseHandler for a description of the API.

Fixes #4933.

### CODE REVIEW

File: java-util/src/main/java/org/apache/druid/java/util/http/client/NettyHttpClient.java [hunk 1]
```diff
@@ -242,22 +264,37 @@ public void messageReceived(ChannelHandlerContext ctx, MessageEvent e)
             }
           }
 
+          private void possiblySuspendReads(ClientResponse<?> response)
+          {
+            if (!response.isContinueReading()) {
+              synchronized (watermarkLock) {
+                suspendWatermark = Math.max(suspendWatermark, currentChunkNum);
+                if (suspendWatermark > resumeWatermark) {
+                  channel.setReadable(false);
```
Comment (himanshug) [inline java-util/src/main/java/org/apache/druid/java/util/http/client/NettyHttpClient.java]: so, this is the magic way of telling netty to stop reading data off of socket without blocking any of the worker threads?

File: java-util/src/main/java/org/apache/druid/java/util/http/client/NettyHttpClient.java [hunk 2]
```diff
@@ -198,11 +205,25 @@ public void messageReceived(ChannelHandlerContext ctx, MessageEvent e)
...
+                      log.debug("[%s] Resumed reads from channel (chunkNum = %,d).", requestDesc, resumeChunkNum);
+                    }
+                  }
+                };
+                response = handler.handleResponse(httpResponse, trafficCop);
                 if (response.isFinished()) {
                   retVal.set((Final) response.getObj());
                 }
 
+                assert currentChunkNum == 0;
```
Comment (himanshug) [inline java-util/src/main/java/org/apache/druid/java/util/http/client/NettyHttpClient.java]: did you intentionally leave it ?

File: java-util/src/main/java/org/apache/druid/java/util/http/client/response/HttpResponseHandler.java [hunk 3]
```diff
@@ -38,17 +38,60 @@
  *
  * Note: if you return a finished ClientResponse object from anything other than the done() method, IntermediateType
  * must be castable to FinalType
+ *
+ * This handler can exert backpressure by returning a response with "continueReading" set to false from handleResponse()
+ * or handleChunk(). In this case, the HTTP client will stop reading soon thereafter. It may not happen immediately, so
+ * be prepared for more handleChunk() calls to happen. To resume reads, call resume() on the TrafficCop provided by
```
Comment (himanshug) [inline java-util/src/main/java/org/apache/druid/java/util/http/client/response/HttpResponseHandler.java]: is this because netty `channel.setReadable(false)` doesn't take effect immediately and netty might deliver one or few more chunks after changing channel readability?

File: java-util/src/main/java/org/apache/druid/java/util/http/client/NettyHttpClient.java (hunk 1 above)
Comment (gianm) [reply java-util/src/main/java/org/apache/druid/java/util/http/client/NettyHttpClient.java]: Yes, it is. It makes netty stop reading from the socket and stop sending new data up the channel.

File: java-util/src/main/java/org/apache/druid/java/util/http/client/NettyHttpClient.java (hunk 2 above)
Comment (gianm) [reply java-util/src/main/java/org/apache/druid/java/util/http/client/NettyHttpClient.java]: I did, it's just a thing that I think should always be true, so I put in an assert to 'document' that.

**Comment by himanshug** [comment]
@gianm that isn't setting the right precedence :)
but yes, it could be left for a future PR.

**Comment by gianm** [comment]
@himanshug, thanks for the review. I raised an issue in https://github.com/apache/incubator-druid/issues/6321 describing how the metric could work.

**Comment by hellobabygogo** [comment]
@gianm 
Hi, gianm. I have a question about broker backpressure. If there are a lot of backpressure queries, will it cause the query thread to be full?

**Comment by himanshug** [comment]
@hellobabygogo  yes , this backpressure means broker will pause to read response data from historicals while it is processing data it already read from them. so, backpressure would propagate all the way to historicals.
