### PR TITLE
Expressions: Fix improper supplier reuse with missing columns.

### LINKED ISSUE #6556: Unexpected results from concat on a real and fake (null) column
So check out this query, note that `channel` exists but `foo` and `bar` do not

```json
{
  "queryType": "topN",
  "dataSource": "wikipedia",
  "intervals": "2015-09-12T00Z/2015-09-13T00Z",
  "granularity": "all",
  "virtualColumns": [
    {
      "type": "expression",
      "name": "v:channel",
      "expression": "concat(\"foo\",\"channel\",\"bar\")",
      "outputType": "STRING"
    }
  ],
  "dimension": {
    "type": "default",
    "dimension": "v:channel",
    "outputName": "channel",
    "outputType": "STRING"
  },
  "aggregations": [
    {
      "name": "count",
      "type": "count"
    }
  ],
  "metric": "count",
  "threshold": 5
}
```

This returns:

```json
[ {
  "timestamp" : "2015-09-12T00:46:00.000Z",
  "result" : [ {
    "count" : 114006,
    "channel" : "enenen"
  }, {
    "count" : 99004,
    "channel" : "vivivi"
  }, {
    "count" : 25022,
    "channel" : "dedede"
  }, {
    "count" : 21191,
    "channel" : "frfrfr"
  }, {
    "count" : 13945,
    "channel" : "rururu"
  } ]
} ]
```

The expected return is:

```json
[ {
  "timestamp" : "2015-09-12T00:46:00.000Z",
  "result" : [ {
    "count" : 114006,
    "channel" : "en"
  }, {
    "count" : 99004,
    "channel" : "vi"
  }, {
    "count" : 25022,
    "channel" : "de"
  }, {
    "count" : 21191,
    "channel" : "fr"
  }, {
    "count" : 13945,
    "channel" : "ru"
  } ]
} ]
```

The issue is obviously with `"expression": "concat(\"foo\",\"channel\",\"bar\")"` maybe there is some buggy optimization? If you have a concat with two actual columns this does not happen.
This appears to be an issue in Druid 0.12.x and 0.13.x.

This is not an issue with SQL as SQL does not let you put in a column that does not exist.
Wait.... that does not sound right.... what if you have a column that exists in one segment and not in another and you query over the segment where the column does not exist?

image

Hot DANG! Seems to be the same issue in SQL... not surprising.

### PR DESCRIPTION
**Pull request by gianm**
ExpressionSelectors has an optimization that skips building a Map
when there is only one input supplier. However, this optimization
should not be used in the case where the is one input supplier but
more than one input identifier (which can happen when only one
input identifier corresponds to an actual column).

Fixes #6556.

### CODE REVIEW

File: processing/src/test/java/org/apache/druid/segment/virtual/ExpressionVirtualColumnTest.java [hunk 1]
```diff
@@ -100,6 +100,12 @@
       ValueType.STRING,
       TestExprMacroTable.INSTANCE
   );
+  private static final ExpressionVirtualColumn ZCONCATNONEXISTENT = new ExpressionVirtualColumn(
```
Comment (leventov) [inline processing/src/test/java/org/apache/druid/segment/virtual/ExpressionVirtualColumnTest.java]: Please add underscores to the name

Comment (gianm) [reply processing/src/test/java/org/apache/druid/segment/virtual/ExpressionVirtualColumnTest.java]: Added, and added them to other statics in the same class.
