### PR TITLE
fix merging of groupBy subtotal spec results

### LINKED ISSUE #8091: groupBy with subtotalsSpec doesn't fully group each set
These two queries (if posed in GroupByQueryRunnerTest) return different results, but I think they should return the same results. The only difference between query 1 and query 2 is that query 2 has an additional dimension that is _not_ referenced in the subtotalsSpec.

I believe the issue is that `GroupByStrategyV2.processSubtotalsSpec` calls `mergeResults` on rows returned by `GroupByRowProcessor.getRowsFromGrouper` for each subtotal dimension list, but this isn't enough to fully group them. The result rows from the grouper are sorted based on the original dimension set, and `mergeResults` only merges adjacent rows.

i.e. Imagine you have two dimensions and they each have values A, B, and C. The original grouper might have rows like this:

AA
AB
BA
BB

Passing "dimsToInclude" with just the second dim would yield these rows from the Grouper:

A
B
A
B

Which cannot be merged by `mergeResults`.

I can think of a couple of fixes:

1. Re-sorting the Grouper rows each time they are pulled out. However, not all Groupers support re-sorting (e.g. SpillingGrouper cannot change its sort order once it has spilled to disk) so it might not always be possible.
2. Using _two_ Groupers (with two merge buffers), one to store the initially grouped rows and one to store subtotal groupings. The act of adding results to the subtotal Grouper will properly and fully group them. Takes more memory but should work in all cases.

Query 1:

```java
    GroupByQuery query = makeQueryBuilder()
        .setDataSource(QueryRunnerTestHelper.dataSource)
        .setQuerySegmentSpec(QueryRunnerTestHelper.firstToThird)
        .setDimensions(
            ImmutableList.of(
                new DefaultDimensionSpec("market", "market")
            )
        )
        .setAggregatorSpecs(Collections.singletonList(QueryRunnerTestHelper.rowsCount))
        .setGranularity(QueryRunnerTestHelper.allGran)
        .setSubtotalsSpec(ImmutableList.of(ImmutableList.of("market")))
        .build();
```

Query 2:

```java
    GroupByQuery query = makeQueryBuilder()
        .setDataSource(QueryRunnerTestHelper.dataSource)
        .setQuerySegmentSpec(QueryRunnerTestHelper.firstToThird)
        .setDimensions(
            ImmutableList.of(
                new DefaultDimensionSpec("quality", "quality"),
                new DefaultDimensionSpec("market", "market")
            )
        )
        .setAggregatorSpecs(Collections.singletonList(QueryRunnerTestHelper.rowsCount))
        .setGranularity(QueryRunnerTestHelper.allGran)
        .setSubtotalsSpec(ImmutableList.of(ImmutableList.of("market")))
        .build();
```

/cc @himanshug

### PR DESCRIPTION
**Pull request by himanshug**
Fixes #8091

Issue for Future Optimization #8108
<hr>

This PR has:
- [ x] been self-reviewed.
- [ x] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [x ] added unit tests or modified existing tests to cover new code paths.

### CODE REVIEW

File: processing/src/main/java/org/apache/druid/query/groupby/strategy/GroupByStrategyV2.java [hunk 1]
```diff
@@ -419,36 +436,81 @@ public Row apply(final Row row)
...
+                          closeables,
+                          false,
+                          false
+                                        )
+                      )
+                  );
+
+                  return Sequences.withBaggage(result, () -> Lists.reverse(closeables).forEach(closeable -> CloseQuietly.close(closeable)));
+                }
+              }, subtotalQuery, null),
```
Comment (gianm) [inline processing/src/main/java/org/apache/druid/query/groupby/strategy/GroupByStrategyV2.java]: Something looks weird about this formatting…

File: processing/src/main/java/org/apache/druid/query/groupby/strategy/GroupByStrategyV2.java [hunk 2]
```diff
@@ -419,36 +436,81 @@ public Row apply(final Row row)
...
-            subtotalQuery
-                             )
-        );
+                @Override
+                public Sequence<Row> run(QueryPlus<Row> queryPlus, Map<String, Object> responseContext)
+                {
+                  return GroupByRowProcessor.getRowsFromGrouper(
+                      queryWithoutSubtotalsSpec,
+                      subtotalSpec,
+                      grouperSupplier
```
Comment (gianm) [inline processing/src/main/java/org/apache/druid/query/groupby/strategy/GroupByStrategyV2.java]: This is `Grouper#1` right? Could you please add a comment where it's initialized, or change its name (`grouperOneSupplier` or something) to make the logic easier to follow?

Comment (gianm) [reply processing/src/main/java/org/apache/druid/query/groupby/strategy/GroupByStrategyV2.java]: Or maybe breaking the method up would make it easier.

I guess what I'm trying to say is when reading, I was wishing it was more clear when we were using `Grouper#1`, when `Grouper#2`, and also who's responsible for closing what.

File: processing/src/main/java/org/apache/druid/query/groupby/strategy/GroupByStrategyV2.java [hunk 3]
```diff
@@ -385,28 +387,43 @@ public Row apply(final Row row)
       Sequence<Row> queryResult
   )
   {
+    // How it works?
```
Comment (gianm) [inline processing/src/main/java/org/apache/druid/query/groupby/strategy/GroupByStrategyV2.java]: Thanks for writing this comment, it helped.

File: processing/src/main/java/org/apache/druid/query/groupby/strategy/GroupByStrategyV2.java [hunk 4]
```diff
@@ -419,36 +436,81 @@ public Row apply(final Row row)
...
+              {
+                @Override
+                public Sequence<Row> run(QueryPlus<Row> queryPlus, Map<String, Object> responseContext)
+                {
+                  List<Closeable> closeables = new ArrayList<>();
+
+                  Sequence<Row> result = GroupByRowProcessor.getRowsFromGrouper(
+                      subtotalQuery,
+                      subtotalSpec,
+                      Suppliers.memoize(() -> GroupByRowProcessor.createGrouper(
```
Comment (gianm) [inline processing/src/main/java/org/apache/druid/query/groupby/strategy/GroupByStrategyV2.java]: I believe this is `Grouper#2`. Could you please make it clear via comment, naming, or splitting out into a separate method?

File: processing/src/main/java/org/apache/druid/query/groupby/strategy/GroupByStrategyV2.java (hunk 1 above)
Comment (himanshug) [reply processing/src/main/java/org/apache/druid/query/groupby/strategy/GroupByStrategyV2.java]: it was passing the intellij formatter , introduced few newlines and it looks better now.

File: processing/src/main/java/org/apache/druid/query/groupby/strategy/GroupByStrategyV2.java (hunk 2 above)
Comment (himanshug) [reply processing/src/main/java/org/apache/druid/query/groupby/strategy/GroupByStrategyV2.java]: renamed variable names to align them better with the comment, it should be easier to follow now.

I thought of breaking the method and then realized most of it is actually method calls which are big because of the number of arguments they take. take a look now, if it still looks difficult then I can try to break it.

File: processing/src/main/java/org/apache/druid/query/groupby/strategy/GroupByStrategyV2.java (hunk 4 above)
Comment (himanshug) [reply processing/src/main/java/org/apache/druid/query/groupby/strategy/GroupByStrategyV2.java]: changed

**Comment by himanshug** [comment]
strict build is broken due to https://github.com/apache/incubator-druid/pull/8138

**Comment by himanshug** [comment]
@gianm can you please review it again ?
