### PR TITLE
fix lookup editor to use lookup tiers instead of historical tiers

### LINKED ISSUE #7646: web-console lookup editor doesn't correctly allow creating new lookups
The web-console lookup editor view uses a dropdown that is populated with [historical tiers from `/druid/coordinator/v1/tiers`](https://github.com/apache/incubator-druid/blob/master/web-console/src/views/lookups-view.tsx#L92) instead of lookup tiers which are unfortunately for the editor a totally different thing. It would be less painful if the [default lookup tier](https://github.com/apache/incubator-druid/blob/master/server/src/main/java/org/apache/druid/query/lookup/LookupListeningAnnouncerConfig.java#L33) config was the same value as the [default historical tier](https://github.com/apache/incubator-druid/blob/master/server/src/main/java/org/apache/druid/client/DruidServer.java#L52) but it is not unfortunately. 

This information can be fetched from a combination of the API calls `/druid/coordinator/v1/lookups/config` and `/druid/coordinator/v1/lookups/config?discover=true` which either returns a list of configured tiers _or_ discovered tiers, the latter of which is [incorrectly listed in the documentation as `/druid/coordinator/v1/lookups?discover=true`](http://druid.io/docs/latest/querying/lookups.html#list-tier-names). 

This dropdowns value should be sourced from the combination of these 2 calls to both have the tiers that have configs, and also tiers which have historical servers associated with them but no defined lookups (maybe we add an `all` query parameter that combines the output of the 2?). 

The input on the editor should also maybe be free-form input to allow new tiers be defined before any historicals are provisioned in that tier, but that seems less important than using the correct set of tiers for the dropdown.

### PR DESCRIPTION
**Pull request by clintropolis**
Fixes #7646, but does not allow freeform defining of new lookup tiers as suggested in that ticket because I'm unsure if it's good UI.

I've also modified the behavior of `/druid/coordinator/v1/lookups/config?discover=true` query parameter to include both discovered and combined lookups to be more useful. If this is undesired behavior and anyone has a use case to have an API call that _only_ returns discovered tiers and _not_ tiers that have defined lookups but no active servers, then I can add another query parameter and hook this composite output up to that instead.

### CODE REVIEW

File: web-console/src/views/lookups-view.tsx [hunk 1]
```diff
@@ -89,7 +89,7 @@ export class LookupsView extends React.Component<LookupsViewProps, LookupsViewSt
   componentDidMount(): void {
     this.lookupsGetQueryManager = new QueryManager({
       processQuery: async (query: string) => {
-        const tiersResp = await axios.get('/druid/coordinator/v1/tiers');
```
Comment (vogievetsky) [inline web-console/src/views/lookups-view.tsx]: Will this always return at least a `__default` tier? That is needed for the dropdown to work nicely.
If not it might make sense to add a UI side check for it...

Comment (clintropolis) [reply web-console/src/views/lookups-view.tsx]: Good question. I think if no active servers to discover are available and no lookups are configured it could return an empty list. 

I've modified the UI side to check for this and at least provide the default lookup tier.. though I suppose there is no guarantee that it will have any available servers once they are discoverable, it still seems like better behavior.

**Comment by clintropolis** [comment]
>Per your comments in #7646 it might make sense to turn the tiers into a free form input. It might make sense to that the "input with suggestions" that is currently inlined in the AutoForm (https://github.com/apache/incubator-druid/blob/master/web-console/src/components/auto-form.tsx#L146) and turn it into a component InputWithSuggestions or SuggestableInput (?) and then reuse it in https://github.com/apache/incubator-druid/blob/master/web-console/src/dialogs/lookup-edit-dialog.tsx#L71 also. Thoughts?

I think this sounds reasonable, though perhaps as a follow-up to this PR to split the refactoring from this fix?

File: web-console/src/views/lookups-view.tsx [hunk 2]
```diff
@@ -38,6 +38,8 @@ import './lookups-view.scss';
 
 const tableColumns: string[] = ['Lookup name', 'Tier', 'Type', 'Version', 'Actions'];
 
+const default_lookup_tier: string = '__default';
```
Comment (vogievetsky) [inline web-console/src/views/lookups-view.tsx]: there should hopefully be a tslint rule to this effect but all variables and constants should be either UPPER_CASE_WITH_UNDERSCORES or snakeCase in this case since this is a 'true' constant it should be the former.

File: web-console/src/views/lookups-view.tsx [hunk 3]
```diff
@@ -89,8 +91,8 @@ export class LookupsView extends React.Component<LookupsViewProps, LookupsViewSt
   componentDidMount(): void {
     this.lookupsGetQueryManager = new QueryManager({
       processQuery: async (query: string) => {
-        const tiersResp = await axios.get('/druid/coordinator/v1/tiers');
-        const tiers = tiersResp.data;
+        const tiersResp = await axios.get('/druid/coordinator/v1/lookups/config?discover=true');
+        const tiers = tiersResp.data && tiersResp.data.lenghth > 0 ? tiersResp.data : [DEFAULT_LOOKUP_TIER];
```
Comment (jon-wei) [inline web-console/src/views/lookups-view.tsx]: Is `lenghth` a typo here?

Comment (clintropolis) [reply web-console/src/views/lookups-view.tsx]: lol yes, good catch :+1:

**Comment by jon-wei** [comment]
Marked "Release Notes" due to the change in the lookup API

**Comment by jihoonson** [comment]
Adding this 0.15.0 since the bug was introduced in https://github.com/apache/incubator-druid/pull/7259 which is in 0.15.0 too.

**Comment by vogievetsky** [comment]
This looks good to merge from my point of view 👍
