### PR TITLE
Fix `is_realtime` column behavior in sys.segments table

### LINKED ISSUE #8142: sys.segment's is_realtime flag once set, is never unset
### Affected Version

0.15

### Description

In the system schema's `sys.segments` table, the `is_realtime` flag is set when a segment is added via `segmentAdded` callback in `DruidSchema`. But it's not unset when a segment is dropped from realtime task and published on historicals. So when `serverSegmentRemoved` is called, the `is_realtime` flag should be unset. 
This was reported here https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/druid-user/t-215-pIJO4/yG9Y5VRLDwAJ

### PR DESCRIPTION
**Pull request by surekhasaharan**
Fixes #8142 

### Description

Update the `isRealtime` flag when a segment is dropped by a realtime task.
In `DruidSchema` added a check in `removeServerSegment()` when none of the replicas is a realtime server type, mark `isRealtime=0`.
Added unit test.
This is marked `incompatible` because the semantics of the `is_realtime` flag for a segment is changed, earlier a segment would be marked realtime, if any realtime task was serving the segment. It's now changed to that a segment would be marked realtime, if _only_ realtime task is serving the segment and if a historical starts serving the segment, it's realtime flag is 0 or false.

----------------------------
This PR has:
- [x] been self-reviewed.
- [x] added documentation for new or modified features or behaviors.
- [x] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [x] added unit tests or modified existing tests to cover new code paths.

### CODE REVIEW

File: sql/src/main/java/org/apache/druid/sql/calcite/schema/DruidSchema.java [hunk 1]
```diff
@@ -431,19 +430,27 @@ void removeSegment(final DataSegment segment)
...
-                                                         .filter(Predicates.not(Predicates.equalTo(server.getName())))
-                                                         .toSet();
+      final Set<DruidServerMetadata> segmentServers = segmentMetadata.getReplicas();
+      final ImmutableSet<DruidServerMetadata> servers = FluentIterable.from(segmentServers)
+                                                                      .filter(Predicates.not(Predicates.equalTo(server)))
+                                                                      .toSet();
+      final DruidServerMetadata realtimeServer = servers.stream()
+                                                  .filter(metadata -> metadata.getType().equals(ServerType.REALTIME))
+                                                  .findAny()
+                                                  .orElse(null);
```
Comment (ccaominh) [inline sql/src/main/java/org/apache/druid/sql/calcite/schema/DruidSchema.java]: Since `findAny()` returns an `Optional`, you could use `Optional.isPresent()` below instead of using `orElse()` to convert to `null`. Another option is to use `anyMatch()` instead of `findAny()`.

File: sql/src/test/java/org/apache/druid/sql/calcite/schema/DruidSchemaTest.java [hunk 2]
```diff
@@ -309,7 +323,7 @@ public void testNullDatasource() throws IOException
                                                        .stream()
                                                        .map(AvailableSegmentMetadata::getSegment)
                                                        .collect(Collectors.toList());
-    Assert.assertEquals(segments.size(), 3);
+    Assert.assertEquals(segments.size(), 4);
```
Comment (ccaominh) [inline sql/src/test/java/org/apache/druid/sql/calcite/schema/DruidSchemaTest.java]: If 4 is the expected value, it should be the first argument. (Similar comment for other occurrences below).

File: sql/src/test/java/org/apache/druid/sql/calcite/schema/DruidSchemaTest.java [hunk 3]
```diff
@@ -343,7 +357,58 @@ public void testNullAvailableSegmentMetadata() throws IOException
...
+    final List<DataSegment> segments = segmentsMetadata.values()
+                                                       .stream()
+                                                       .map(AvailableSegmentMetadata::getSegment)
+                                                       .collect(Collectors.toList());
+    // find the only realtime segment with datasource "foo3"
+    final DataSegment existingSegment = segments.stream()
+                                                .filter(segment -> segment.getDataSource().equals("foo3"))
+                                                .findFirst()
+                                                .orElse(null);
+
```
Comment (ccaominh) [inline sql/src/test/java/org/apache/druid/sql/calcite/schema/DruidSchemaTest.java]: Do you want to assert `existingSegment` is not `null`? (similar comment for other occurrences below)

File: sql/src/test/java/org/apache/druid/sql/calcite/schema/DruidSchemaTest.java [hunk 4]
```diff
@@ -343,7 +357,58 @@ public void testNullAvailableSegmentMetadata() throws IOException
...
+    final AvailableSegmentMetadata metadata = segmentsMetadata.get(existingSegment.getId());
+    Assert.assertEquals(metadata.isRealtime(), 1L);
```
Comment (ccaominh) [inline sql/src/test/java/org/apache/druid/sql/calcite/schema/DruidSchemaTest.java]: Make 1L the first argument as it's the expected value.

File: sql/src/main/java/org/apache/druid/sql/calcite/schema/DruidSchema.java (hunk 1 above)
Comment (surekhasaharan) [reply sql/src/main/java/org/apache/druid/sql/calcite/schema/DruidSchema.java]: ah, sure, i used `Optional.isPresent()`

File: sql/src/test/java/org/apache/druid/sql/calcite/schema/DruidSchemaTest.java (hunk 2 above)
Comment (surekhasaharan) [reply sql/src/test/java/org/apache/druid/sql/calcite/schema/DruidSchemaTest.java]: fixed here and other places.

File: sql/src/test/java/org/apache/druid/sql/calcite/schema/DruidSchemaTest.java (hunk 3 above)
Comment (surekhasaharan) [reply sql/src/test/java/org/apache/druid/sql/calcite/schema/DruidSchemaTest.java]: yup

File: sql/src/main/java/org/apache/druid/sql/calcite/schema/DruidSchema.java [hunk 5]
```diff
@@ -431,19 +431,29 @@ void removeSegment(final DataSegment segment)
...
+          .from(segmentServers)
+          .filter(Predicates.not(Predicates.equalTo(server)))
+          .toSet();
+      final Optional<DruidServerMetadata> realtimeServer = servers
+          .stream()
+          .filter(metadata -> metadata.getType().equals(ServerType.REALTIME))
+          .findAny();
+
+      // if there is no realtime server in the replicas, isRealtime flag should be unset
+      long isRealtime = realtimeServer.isPresent() ? 1 : 0;
```
Comment (clintropolis) [inline sql/src/main/java/org/apache/druid/sql/calcite/schema/DruidSchema.java]: [Apologies for missing this original discussion](https://github.com/apache/incubator-druid/pull/6094#discussion_r210661609), but is this the most useful thing for the `is_realtime` flag to mean, where it reports true if _any_ of the servers serving a segment is a realtime task?

It might be more useful for `is_realtime` to report true if it is _only_ available on realtime tasks, and false if any server serving the segment is a historical, since that is how the broker will behave at query time (#4764). I think this would probably involve doing this as part of `addSegment` instead of `removeSegment`.

Comment (surekhasaharan) [reply sql/src/main/java/org/apache/druid/sql/calcite/schema/DruidSchema.java]: You have a point, i think i sort of agree, it'll make `is_realtime` more intuitive for users.  The docs for `is_realtime` [here](https://druid.apache.org/docs/latest/querying/sql) say this flag is `1 if this segment is being served on any type of realtime tasks`, that'll need to change. Yeah, with the changed semantics of `is_realtime`, the flag will be unset when `addSegment` is called a second time via a historical. May be it should be updated in `removeSegment` as well, but the check will be if there is any historical server in the replicas, unset this flag.

Comment (surekhasaharan) [reply sql/src/main/java/org/apache/druid/sql/calcite/schema/DruidSchema.java]: This change will make it `incompatible` with previous behavior, which I hope is okay, unless someone is relying on that behavior of `is_realtime`.

Comment (jon-wei) [reply sql/src/main/java/org/apache/druid/sql/calcite/schema/DruidSchema.java]: > It might be more useful for is_realtime to report true if it is only available on realtime tasks, and false if any server serving the segment is a historical

That sounds good to me

Comment (gianm) [reply sql/src/main/java/org/apache/druid/sql/calcite/schema/DruidSchema.java]: I think the idea I had in the previous conversation was motivated by `is_realtime` being false meaning that the segment has completely flushed out of the realtime system. I thought it'd be useful for finding segments where handoff is lingering for some reason.

If we change it to what you are proposing, @clintropolis, then it'd be somewhat harder to find segments where handoff is lingering (but still possible by joining `segments` and `servers`). But it'd be easier to find segments where handoff has progressed far enough that a historical has loaded the segment.

Six of one, half dozen of the other.

I am okay with either approach, so long as it's clearly documented what the behavior should be. I don't think the fact that the change would be theoretically incompatible is a big deal, since the column is buggy enough that it doesn't work anyway right now.

**Comment by dclim** [comment]
👍
