### PR TITLE
Fix LookupSerdeModule double-binding in Coordinator-as-Overlord mode.

### LINKED ISSUE #7762: Regression: Coordinator startup fails with exception
### Affected Version
0.14.0-iap10

### Last working version

0.14.0-iap8

### Description

No configuration changes were made when upgrading versions

```
Exception in thread "main" com.google.inject.CreationException: Unable to create injector, see the following errors:
1) A binding to com.google.common.base.Supplier<org.apache.druid.query.lookup.LookupConfig> was already configured at org.apache.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:151) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.query.lookup.LookupSerdeModule).
  at org.apache.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:151) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.query.lookup.LookupSerdeModule)
2) A binding to org.apache.druid.query.lookup.LookupConfig was already configured at org.apache.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:152) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.query.lookup.LookupSerdeModule).
  at org.apache.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:152) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.query.lookup.LookupSerdeModule)
2 errors
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at org.apache.druid.initialization.Initialization.makeInjectorWithModules(Initialization.java:422)
	at org.apache.druid.cli.GuiceRunnable.makeInjector(GuiceRunnable.java:69)
	at org.apache.druid.cli.ServerRunnable.run(ServerRunnable.java:57)
	at org.apache.druid.cli.Main.main(Main.java:118)
```

### PR DESCRIPTION
**Pull request by gianm**
Fixes #7762.

### CODE REVIEW

File: services/src/main/java/org/apache/druid/cli/CliCoordinator.java [hunk 1]
```diff
@@ -272,10 +272,12 @@ public LoadQueueTaskMaster getLoadQueueTaskMaster(
...
     );
 
-    modules.add(new LookupSerdeModule());
-
     if (beOverlord) {
       modules.addAll(new CliOverlord().getModules(false));
+    } else {
+      // Only add LookupSerdeModule if !beOverlord, since CliOverlord includes it, and having two copies causes
+      // the injector to get confused due to having multiple bindings for the same classes.
+      modules.add(new LookupSerdeModule());
```
Comment (himanshug) [inline services/src/main/java/org/apache/druid/cli/CliCoordinator.java]: that is why `CliOverloard.getModules(boolean standalone)` takes the standalone flag also, so that we can take care of these things in there if/when needed.
