### PR TITLE
Adjust BufferAggregator.get() impls to return copies

### LINKED ISSUE #7461: HLLSketchBuild: Intermittent errors at query time
### Affected Version

Observed in Druid 0.13.0-incubating-iap9, an Imply build, but one that has no differences from 0.13.0-incubating in the `extensions-core/datasketches` tree. Btw, both use sketches-core 0.10.3.

### Description

I ran this query 200 times and saw two errors on historicals:

```json
{
  "queryType": "topN",
  "dataSource": "my-ds-name",
  "intervals": [
    "2019-03-01T22:45:26.000Z/2019-03-08T22:45:26.000Z"
  ],
  "granularity": {
    "type": "period",
    "period": "P1W",
    "origin": "2019-03-01T22:45:26.000Z"
  },
  "dimension": "geo.city",
  "threshold": 200,
  "metric": "distinctUserId",
  "aggregations": [
    {
      "name": "distinctUserId",
      "type": "HLLSketchBuild",
      "fieldName": "userId",
      "lgK": 12,
      "tgtHllType": "HLL_4"
    }
  ]
}
```

The first was:

```
java.lang.NullPointerException
        at com.yahoo.sketches.hll.DirectHll4Array$DirectHll4Iterator.value(DirectHll4Array.java:173) ~[?:?]
        at com.yahoo.sketches.hll.HllPairIterator.nextValid(HllPairIterator.java:75) ~[?:?]
        at com.yahoo.sketches.hll.Union.unionImpl(Union.java:374) ~[?:?]
        at com.yahoo.sketches.hll.Union.update(Union.java:264) ~[?:?]
        at org.apache.druid.query.aggregation.datasketches.hll.HllSketchAggregatorFactory.combine(HllSketchAggregatorFactory.java:123) ~[?:?]
        at org.apache.druid.query.aggregation.datasketches.hll.HllSketchBuildAggregatorFactory.combine(HllSketchBuildAggregatorFactory.java:40) ~[?:?]
        at org.apache.druid.query.aggregation.datasketches.hll.HllSketchAggregatorFactory.combine(HllSketchAggregatorFactory.java:44) ~[?:?]
        at org.apache.druid.query.topn.TopNBinaryFn.apply(TopNBinaryFn.java:103) ~[druid-processing-0.13.0-incubating-iap9.jar:0.13.0-incubating-iap9]
```

And the second was:

```
java.lang.NegativeArraySizeException
        at com.yahoo.sketches.hll.Hll4Array.<init>(Hll4Array.java:32) ~[?:?]
        at com.yahoo.sketches.hll.Conversions.convertToHll4(Conversions.java:20) ~[?:?]
        at com.yahoo.sketches.hll.AbstractHllArray.copyAs(AbstractHllArray.java:34) ~[?:?]
        at com.yahoo.sketches.hll.AbstractHllArray.copyAs(AbstractHllArray.java:17) ~[?:?]
        at com.yahoo.sketches.hll.HllSketch.copyAs(HllSketch.java:241) ~[?:?]
        at com.yahoo.sketches.hll.Union.getResult(Union.java:179) ~[?:?]
        at org.apache.druid.query.aggregation.datasketches.hll.HllSketchAggregatorFactory.combine(HllSketchAggregatorFactory.java:124) ~[?:?]
        at org.apache.druid.query.aggregation.datasketches.hll.HllSketchBuildAggregatorFactory.combine(HllSketchBuildAggregatorFactory.java:40) ~[?:?]
        at org.apache.druid.query.aggregation.datasketches.hll.HllSketchAggregatorFactory.combine(HllSketchAggregatorFactory.java:44) ~[?:?]
        at org.apache.druid.query.topn.TopNBinaryFn.apply(TopNBinaryFn.java:103) ~[druid-processing-0.13.0-incubating-iap9.jar:0.13.0-incubating-iap9]
```

### PR DESCRIPTION
**Pull request by jon-wei**
Fixes #7461

This PR adjusts `HllSketchBuildBufferAggregator`, `DoublesSketchBuildBufferAggregator`, and `BaseBloomFilterBufferAggregator` to return on-heap copies of the aggregator's objects.

### CODE REVIEW

**Comment by gianm** [comment]
It seems like `compact()` would work on UpdateDoublesSketch.

File: processing/src/main/java/org/apache/druid/query/aggregation/BufferAggregator.java [hunk 1]
```diff
@@ -72,7 +72,9 @@
    *
    * Converts the given byte buffer representation into an intermediate aggregate Object
    *
-   * <b>Implementations must not change the position, limit or mark of the given buffer</b>
+   * <b>Implementations must not change the position, limit or mark of the given buffer.</b>
+   *
+   * <b>The object returned must not have any references to the given buffer (i.e., make a copy).</b>
```
Comment (gianm) [inline processing/src/main/java/org/apache/druid/query/aggregation/BufferAggregator.java]: I'd include rationale for this: it's because the object returned by `get` may live beyond the lifetime of the underlying buffer.

Comment (jon-wei) [reply processing/src/main/java/org/apache/druid/query/aggregation/BufferAggregator.java]: Added the rationale here.

**Comment by jon-wei** [comment]
I updated this to use `compact()` and added a note on mutability of return objects for BufferAggregator.get()
